package main

import (
	"context"
	"crypto/tls"
	"errors"
	"flag"
	"fmt"
	"log/slog"
	"net"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/innerwall-dev/innerwall/internal/ca/fileca"
	"github.com/innerwall-dev/innerwall/internal/compiler"
	"github.com/innerwall-dev/innerwall/internal/enroll"
	"github.com/innerwall-dev/innerwall/internal/flowstore"
	"github.com/innerwall-dev/innerwall/internal/gateway"
	"github.com/innerwall-dev/innerwall/internal/ingest"
	"github.com/innerwall-dev/innerwall/internal/store"
	"github.com/innerwall-dev/innerwall/ui"
)

const (
	serverCertFile = "server.crt"
	serverKeyFile  = "server.key"
)

func runServe(ctx context.Context, args []string) error {
	fs := flag.NewFlagSet("innerwall serve", flag.ContinueOnError)
	listen := fs.String("listen", defaultListen, "address for the agent gateway (gRPC over TLS)")
	caDir := fs.String("ca-dir", envOr(envCADir, defaultCADir), "directory holding the signing authority (see `innerwall ca init`)")
	tlsCert := fs.String("tls-cert", "", "server certificate PEM (default <ca-dir>/server.crt)")
	tlsKey := fs.String("tls-key", "", "server key PEM (default <ca-dir>/server.key)")
	leafTTL := fs.Duration("leaf-ttl", enroll.DefaultLeafTTL, "lifetime of issued workload credentials")
	dbURL := fs.String("database-url", "", "Postgres connection string (default $"+envDatabaseURL+")")
	migrate := fs.Bool("migrate", false, "apply pending database migrations before serving")
	initCA := fs.Bool("init-ca", false, "create the signing authority and server certificate if the CA directory holds none (development convenience)")
	tlsHosts := fs.String("tls-hosts", "localhost,127.0.0.1", "hosts for the server certificate generated by --init-ca")
	flowRetention := fs.Duration("flow-retention", flowstore.DefaultRetention, "age beyond which stored flow windows are deleted; totals are kept")
	flowRetentionInterval := fs.Duration("flow-retention-interval", flowstore.DefaultRetentionInterval, "period between flow retention runs")
	if err := fs.Parse(args); err != nil {
		return err
	}

	log := slog.New(slog.NewTextHandler(os.Stderr, nil))
	slog.SetDefault(log)

	url, err := databaseURL(*dbURL)
	if err != nil {
		return err
	}
	if *migrate {
		if err := store.Migrate(ctx, url); err != nil {
			return err
		}
		log.Info("migrations applied")
	}
	st, err := store.Open(ctx, url)
	if err != nil {
		return err
	}
	defer st.Close()

	if *initCA {
		if err := initAuthority(*caDir, strings.Split(*tlsHosts, ","), fileca.DefaultRootTTL, defaultServerTTL, log); err != nil && !errors.Is(err, fileca.ErrExists) {
			return err
		}
	}
	authority, err := fileca.Open(*caDir)
	if err != nil {
		return err
	}
	bundle, err := authority.Bundle(ctx)
	if err != nil {
		return err
	}
	if *tlsCert == "" {
		*tlsCert = filepath.Join(*caDir, serverCertFile)
	}
	if *tlsKey == "" {
		*tlsKey = filepath.Join(*caDir, serverKeyFile)
	}
	serverCert, err := tls.LoadX509KeyPair(*tlsCert, *tlsKey)
	if err != nil {
		return fmt.Errorf("loading server certificate: %w", err)
	}
	tlsCfg, err := gateway.ServerTLSConfig(serverCert, bundle)
	if err != nil {
		return err
	}

	svc := &enroll.Service{Store: st, Authority: authority, LeafTTL: *leafTTL}
	engine := &compiler.Engine{Store: st, Log: log}
	srv := gateway.New(gateway.Deps{
		Enroll:   svc,
		Registry: st,
		Policies: st,
		Engine:   engine,
		Events:   st,
		Ingest:   &ingest.Service{Directory: st, Flows: st.Flows(), Log: log.With("service", "ingest")},
		Log:      log,
	})
	retention := &flowstore.Retention{Store: st.Flows(), Horizon: *flowRetention, Interval: *flowRetentionInterval, Log: log.With("job", "flow-retention")}
	grpcServer := gateway.NewGRPCServer(tlsCfg, srv)
	// Every workload's rendered policy must exist before its stream can
	// be served; a fresh database or one migrated from an earlier schema
	// renders here once.
	if _, err := engine.Render(ctx); err != nil {
		return err
	}

	lis, err := net.Listen("tcp", *listen)
	if err != nil {
		return fmt.Errorf("listening on %s: %w", *listen, err)
	}
	uiEntries, _ := ui.Assets.ReadDir("dist")
	log.Info("control plane serving", "version", version, "listen", lis.Addr().String(), "leaf_ttl", leafTTL.String(), "flow_retention", flowRetention.String(), "embedded_ui_entries", len(uiEntries))

	errc := make(chan error, 1)
	go func() { errc <- grpcServer.Serve(lis) }()
	// Route render announcements to live streams until shutdown.
	go func() {
		if err := srv.Run(ctx); err != nil {
			log.Error("policy announcement listener stopped", "error", err)
		}
	}()
	// Prune aged flow windows on a schedule; one replica at a time.
	go func() { _ = retention.Run(ctx) }()
	select {
	case <-ctx.Done():
		log.Info("shutting down")
		done := make(chan struct{})
		go func() { grpcServer.GracefulStop(); close(done) }()
		select {
		case <-done:
		case <-time.After(10 * time.Second):
			grpcServer.Stop()
		}
		return nil
	case err := <-errc:
		return err
	}
}
