package main

import (
	"context"
	"crypto/tls"
	"errors"
	"flag"
	"fmt"
	"io/fs"
	"log/slog"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/innerwall-dev/innerwall/internal/api"
	"github.com/innerwall-dev/innerwall/internal/ca/fileca"
	"github.com/innerwall-dev/innerwall/internal/compiler"
	"github.com/innerwall-dev/innerwall/internal/enroll"
	"github.com/innerwall-dev/innerwall/internal/flowstore"
	"github.com/innerwall-dev/innerwall/internal/gateway"
	"github.com/innerwall-dev/innerwall/internal/ingest"
	"github.com/innerwall-dev/innerwall/internal/operator"
	"github.com/innerwall-dev/innerwall/internal/readmodel"
	"github.com/innerwall-dev/innerwall/internal/store"
	"github.com/innerwall-dev/innerwall/ui"
)

const (
	serverCertFile = "server.crt"
	serverKeyFile  = "server.key"
)

// consoleServed reports whether the embedded tree holds a console entry
// point, for the startup log.
func consoleServed(tree fs.FS) bool {
	if tree == nil {
		return false
	}
	_, err := fs.Stat(tree, "index.html")
	return err == nil
}

func runServe(ctx context.Context, args []string) error {
	fs := flag.NewFlagSet("innerwall serve", flag.ContinueOnError)
	listen := fs.String("listen", defaultListen, "address for the agent gateway (gRPC over TLS)")
	operatorListen := fs.String("operator-listen", defaultOperatorListen, "address for the operator surface (REST/JSON façade and console, TLS only)")
	operatorTLSCert := fs.String("operator-tls-cert", "", "operator listener certificate PEM (with --operator-tls-key; default: a self-signed certificate persisted in <ca-dir>)")
	operatorTLSKey := fs.String("operator-tls-key", "", "operator listener key PEM (with --operator-tls-cert)")
	site := fs.String("site", envOr(envSite, ""), "site label the console header shows (default $"+envSite+")")
	caDir := fs.String("ca-dir", envOr(envCADir, defaultCADir), "directory holding the signing authority (see `innerwall ca init`)")
	tlsCert := fs.String("tls-cert", "", "server certificate PEM (default <ca-dir>/server.crt)")
	tlsKey := fs.String("tls-key", "", "server key PEM (default <ca-dir>/server.key)")
	leafTTL := fs.Duration("leaf-ttl", enroll.DefaultLeafTTL, "lifetime of issued workload credentials")
	dbURL := fs.String("database-url", "", "Postgres connection string (default $"+envDatabaseURL+")")
	migrate := fs.Bool("migrate", false, "apply pending database migrations before serving")
	initCA := fs.Bool("init-ca", false, "create the signing authority and server certificate if the CA directory holds none (development convenience)")
	tlsHosts := fs.String("tls-hosts", "localhost,127.0.0.1", "hosts for the server certificate generated by --init-ca and for a generated operator certificate")
	flowRetention := fs.Duration("flow-retention", flowstore.DefaultRetention, "age beyond which stored flow windows are deleted; totals are kept")
	flowRetentionInterval := fs.Duration("flow-retention-interval", flowstore.DefaultRetentionInterval, "period between flow retention runs")
	if err := fs.Parse(args); err != nil {
		return err
	}

	log := slog.New(slog.NewTextHandler(os.Stderr, nil))
	slog.SetDefault(log)

	url, err := databaseURL(*dbURL)
	if err != nil {
		return err
	}
	if *migrate {
		if err := store.Migrate(ctx, url); err != nil {
			return err
		}
		log.Info("migrations applied")
	}
	st, err := store.Open(ctx, url)
	if err != nil {
		return err
	}
	defer st.Close()

	if *initCA {
		if err := initAuthority(*caDir, strings.Split(*tlsHosts, ","), fileca.DefaultRootTTL, defaultServerTTL, log); err != nil && !errors.Is(err, fileca.ErrExists) {
			return err
		}
	}
	authority, err := fileca.Open(*caDir)
	if err != nil {
		return err
	}
	bundle, err := authority.Bundle(ctx)
	if err != nil {
		return err
	}
	if *tlsCert == "" {
		*tlsCert = filepath.Join(*caDir, serverCertFile)
	}
	if *tlsKey == "" {
		*tlsKey = filepath.Join(*caDir, serverKeyFile)
	}
	serverCert, err := tls.LoadX509KeyPair(*tlsCert, *tlsKey)
	if err != nil {
		return fmt.Errorf("loading server certificate: %w", err)
	}
	tlsCfg, err := gateway.ServerTLSConfig(serverCert, bundle)
	if err != nil {
		return err
	}

	// The operator listener serves TLS or it does not serve (ADR-0021): a
	// configured pair is loaded, and absent one a self-signed certificate
	// is generated on first start and persisted beside the authority.
	operatorCert, err := api.ListenerCertificate(*operatorTLSCert, *operatorTLSKey, *caDir, strings.Split(*tlsHosts, ","), time.Now(), log.With("listener", "operator"))
	if err != nil {
		return err
	}
	operators := &operator.Service{Store: st}
	reads := &readmodel.Reader{Store: st, Flows: st.Flows()}
	// The console is served at every path outside the API prefix; a
	// build without one (the noconsole tag, or a checkout where `make
	// console` has not run) answers those paths with a marked problem.
	console := ui.Console()
	apiSrv := api.New(api.Deps{Operators: operators, Reads: reads, Site: *site, Console: console, Log: log.With("service", "api")})
	httpServer := api.NewHTTPServer(api.ServerTLSConfig(operatorCert), apiSrv.Handler())

	svc := &enroll.Service{Store: st, Authority: authority, LeafTTL: *leafTTL}
	engine := &compiler.Engine{Store: st, Log: log}
	srv := gateway.New(gateway.Deps{
		Enroll:   svc,
		Registry: st,
		Policies: st,
		Engine:   engine,
		Events:   st,
		Ingest:   &ingest.Service{Directory: st, Flows: st.Flows(), Log: log.With("service", "ingest")},
		Log:      log,
	})
	retention := &flowstore.Retention{
		Store:    st.Flows(),
		Horizon:  *flowRetention,
		Interval: *flowRetentionInterval,
		// Expired operator sessions ride the same schedule (ADR-0021).
		Pruners: []flowstore.Pruner{flowstore.PrunerFunc(operators.PruneSessions)},
		Log:     log.With("job", "flow-retention"),
	}
	grpcServer := gateway.NewGRPCServer(tlsCfg, srv)
	// Every workload's rendered policy must exist before its stream can
	// be served; a fresh database or one migrated from an earlier schema
	// renders here once.
	if _, err := engine.Render(ctx); err != nil {
		return err
	}

	lis, err := net.Listen("tcp", *listen)
	if err != nil {
		return fmt.Errorf("listening on %s: %w", *listen, err)
	}
	operatorLis, err := net.Listen("tcp", *operatorListen)
	if err != nil {
		return fmt.Errorf("listening on %s: %w", *operatorListen, err)
	}
	log.Info("control plane serving", "version", version, "listen", lis.Addr().String(), "operator_listen", operatorLis.Addr().String(), "site", *site, "leaf_ttl", leafTTL.String(), "flow_retention", flowRetention.String(), "console", consoleServed(console))

	errc := make(chan error, 2)
	go func() { errc <- grpcServer.Serve(lis) }()
	go func() {
		if err := httpServer.ServeTLS(operatorLis, "", ""); err != nil && !errors.Is(err, http.ErrServerClosed) {
			errc <- err
		}
	}()
	// Route render announcements to live streams until shutdown.
	go func() {
		if err := srv.Run(ctx); err != nil {
			log.Error("policy announcement listener stopped", "error", err)
		}
	}()
	// Prune aged flow windows on a schedule; one replica at a time.
	go func() { _ = retention.Run(ctx) }()
	select {
	case <-ctx.Done():
		log.Info("shutting down")
		stopCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		done := make(chan struct{})
		go func() { grpcServer.GracefulStop(); close(done) }()
		if err := httpServer.Shutdown(stopCtx); err != nil {
			_ = httpServer.Close()
		}
		select {
		case <-done:
		case <-stopCtx.Done():
			grpcServer.Stop()
		}
		return nil
	case err := <-errc:
		return err
	}
}
