// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: address_groups.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addAddressGroupCIDR = `-- name: AddAddressGroupCIDR :exec
INSERT INTO address_group_cidrs (address_group_id, cidr)
VALUES ($1, $2)
`

type AddAddressGroupCIDRParams struct {
	AddressGroupID uuid.UUID
	Cidr           string
}

func (q *Queries) AddAddressGroupCIDR(ctx context.Context, arg AddAddressGroupCIDRParams) error {
	_, err := q.db.Exec(ctx, addAddressGroupCIDR, arg.AddressGroupID, arg.Cidr)
	return err
}

const countRulesReferencingAddressGroup = `-- name: CountRulesReferencingAddressGroup :one
SELECT count(*) FROM rule_peers
WHERE address_group_id = $1
`

func (q *Queries) CountRulesReferencingAddressGroup(ctx context.Context, addressGroupID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRulesReferencingAddressGroup, addressGroupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAddressGroup = `-- name: CreateAddressGroup :exec

INSERT INTO address_groups (id, name, created_at, updated_at)
VALUES ($1, $2, $3, $3)
`

type CreateAddressGroupParams struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

// Address groups: named CIDR sets for peers that are not managed workloads
// (ADR-0018).
func (q *Queries) CreateAddressGroup(ctx context.Context, arg CreateAddressGroupParams) error {
	_, err := q.db.Exec(ctx, createAddressGroup, arg.ID, arg.Name, arg.CreatedAt)
	return err
}

const deleteAddressGroup = `-- name: DeleteAddressGroup :execrows
DELETE FROM address_groups
WHERE id = $1
`

func (q *Queries) DeleteAddressGroup(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAddressGroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAddressGroupCIDRs = `-- name: DeleteAddressGroupCIDRs :exec
DELETE FROM address_group_cidrs
WHERE address_group_id = $1
`

func (q *Queries) DeleteAddressGroupCIDRs(ctx context.Context, addressGroupID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAddressGroupCIDRs, addressGroupID)
	return err
}

const getAddressGroup = `-- name: GetAddressGroup :one
SELECT id, region_id, name, created_at, updated_at FROM address_groups
WHERE id = $1
`

func (q *Queries) GetAddressGroup(ctx context.Context, id uuid.UUID) (AddressGroup, error) {
	row := q.db.QueryRow(ctx, getAddressGroup, id)
	var i AddressGroup
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAddressGroupCIDRs = `-- name: ListAddressGroupCIDRs :many
SELECT address_group_id, cidr FROM address_group_cidrs
WHERE address_group_id = $1
ORDER BY cidr
`

func (q *Queries) ListAddressGroupCIDRs(ctx context.Context, addressGroupID uuid.UUID) ([]AddressGroupCidr, error) {
	rows, err := q.db.Query(ctx, listAddressGroupCIDRs, addressGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AddressGroupCidr{}
	for rows.Next() {
		var i AddressGroupCidr
		if err := rows.Scan(&i.AddressGroupID, &i.Cidr); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAddressGroups = `-- name: ListAddressGroups :many
SELECT id, region_id, name, created_at, updated_at FROM address_groups
ORDER BY name, id
`

func (q *Queries) ListAddressGroups(ctx context.Context) ([]AddressGroup, error) {
	rows, err := q.db.Query(ctx, listAddressGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AddressGroup{}
	for rows.Next() {
		var i AddressGroup
		if err := rows.Scan(
			&i.ID,
			&i.RegionID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAddressGroupCIDRs = `-- name: ListAllAddressGroupCIDRs :many
SELECT address_group_id, cidr FROM address_group_cidrs
ORDER BY address_group_id, cidr
`

func (q *Queries) ListAllAddressGroupCIDRs(ctx context.Context) ([]AddressGroupCidr, error) {
	rows, err := q.db.Query(ctx, listAllAddressGroupCIDRs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AddressGroupCidr{}
	for rows.Next() {
		var i AddressGroupCidr
		if err := rows.Scan(&i.AddressGroupID, &i.Cidr); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAddressGroup = `-- name: UpdateAddressGroup :execrows
UPDATE address_groups
SET name = $2, updated_at = $3
WHERE id = $1
`

type UpdateAddressGroupParams struct {
	ID        uuid.UUID
	Name      string
	UpdatedAt time.Time
}

func (q *Queries) UpdateAddressGroup(ctx context.Context, arg UpdateAddressGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAddressGroup, arg.ID, arg.Name, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
