// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package db

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const insertFlowGap = `-- name: InsertFlowGap :batchexec

INSERT INTO flow_gaps (workload_id, kind, source, gap_from, gap_to, lost_count)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (workload_id, kind, source, gap_from, gap_to) DO NOTHING
`

type InsertFlowGapBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertFlowGapParams struct {
	WorkloadID uuid.UUID
	Kind       int32
	Source     int32
	GapFrom    time.Time
	GapTo      time.Time
	LostCount  pgtype.Int8
}

// --- evidence gaps -------------------------------------------------------------
//
// Intervals in which a workload's evidence is known to be incomplete
// (ADR-0019 as amended). Delivery is at least once: an interval repeated
// exactly is stored once.
func (q *Queries) InsertFlowGap(ctx context.Context, arg []InsertFlowGapParams) *InsertFlowGapBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.WorkloadID,
			a.Kind,
			a.Source,
			a.GapFrom,
			a.GapTo,
			a.LostCount,
		}
		batch.Queue(insertFlowGap, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertFlowGapBatchResults{br, len(arg), false}
}

func (b *InsertFlowGapBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertFlowGapBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertFlowTotal = `-- name: UpsertFlowTotal :batchexec
INSERT INTO flow_totals (
    workload_id, peer_kind, peer_key, peer_labels,
    dst_port, protocol, direction, decision, matched_rule_id,
    first_seen, last_seen, connection_count, byte_count, window_count
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9,
    $10, $11, $12, $13, 1
)
ON CONFLICT (workload_id, peer_kind, peer_key, dst_port, protocol, direction, decision) DO UPDATE
SET peer_labels      = EXCLUDED.peer_labels,
    matched_rule_id  = EXCLUDED.matched_rule_id,
    first_seen       = LEAST(flow_totals.first_seen, EXCLUDED.first_seen),
    last_seen        = GREATEST(flow_totals.last_seen, EXCLUDED.last_seen),
    connection_count = flow_totals.connection_count + EXCLUDED.connection_count,
    byte_count       = flow_totals.byte_count + EXCLUDED.byte_count,
    window_count     = flow_totals.window_count + 1
`

type UpsertFlowTotalBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertFlowTotalParams struct {
	WorkloadID      uuid.UUID
	PeerKind        int32
	PeerKey         string
	PeerLabels      []byte
	DstPort         int32
	Protocol        int32
	Direction       int32
	Decision        int32
	MatchedRuleID   string
	FirstSeen       time.Time
	LastSeen        time.Time
	ConnectionCount int64
	ByteCount       int64
}

func (q *Queries) UpsertFlowTotal(ctx context.Context, arg []UpsertFlowTotalParams) *UpsertFlowTotalBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.WorkloadID,
			a.PeerKind,
			a.PeerKey,
			a.PeerLabels,
			a.DstPort,
			a.Protocol,
			a.Direction,
			a.Decision,
			a.MatchedRuleID,
			a.FirstSeen,
			a.LastSeen,
			a.ConnectionCount,
			a.ByteCount,
		}
		batch.Queue(upsertFlowTotal, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertFlowTotalBatchResults{br, len(arg), false}
}

func (b *UpsertFlowTotalBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertFlowTotalBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
