// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertFlowWindows implements pgx.CopyFromSource.
type iteratorForInsertFlowWindows struct {
	rows                 []InsertFlowWindowsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertFlowWindows) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertFlowWindows) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].WorkloadID,
		r.rows[0].WindowStart,
		r.rows[0].WindowEnd,
		r.rows[0].PeerKind,
		r.rows[0].PeerKey,
		r.rows[0].PeerLabels,
		r.rows[0].SrcAddress,
		r.rows[0].DstAddress,
		r.rows[0].DstPort,
		r.rows[0].Protocol,
		r.rows[0].Direction,
		r.rows[0].Decision,
		r.rows[0].MatchedRuleID,
		r.rows[0].ConnectionCount,
		r.rows[0].ByteCount,
		r.rows[0].FirstSeen,
		r.rows[0].LastSeen,
		r.rows[0].ProcessName,
	}, nil
}

func (r iteratorForInsertFlowWindows) Err() error {
	return nil
}

// Flow storage (ADR-0009, ADR-0019). These are the only statements that
// touch flow_windows and flow_totals; every caller goes through the
// FlowStore interface in internal/flowstore.
func (q *Queries) InsertFlowWindows(ctx context.Context, arg []InsertFlowWindowsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"flow_windows"}, []string{"workload_id", "window_start", "window_end", "peer_kind", "peer_key", "peer_labels", "src_address", "dst_address", "dst_port", "protocol", "direction", "decision", "matched_rule_id", "connection_count", "byte_count", "first_seen", "last_seen", "process_name"}, &iteratorForInsertFlowWindows{rows: arg})
}
