// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flows.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countFlowWindows = `-- name: CountFlowWindows :one
SELECT count(*) FROM flow_windows
`

func (q *Queries) CountFlowWindows(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFlowWindows)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteFlowWindowsBefore = `-- name: DeleteFlowWindowsBefore :execrows
DELETE FROM flow_windows
WHERE id IN (
    SELECT oldest.id FROM flow_windows AS oldest
    WHERE oldest.window_start < $1
    ORDER BY oldest.window_start
    LIMIT $2
)
`

type DeleteFlowWindowsBeforeParams struct {
	Horizon   time.Time
	BatchSize int32
}

// Retention: one bounded batch of the oldest windows before the horizon.
// The caller loops until a batch deletes nothing, so no single statement
// holds locks for the whole backlog (ADR-0019).
func (q *Queries) DeleteFlowWindowsBefore(ctx context.Context, arg DeleteFlowWindowsBeforeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFlowWindowsBefore, arg.Horizon, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

type InsertFlowWindowsParams struct {
	WorkloadID      uuid.UUID
	WindowStart     time.Time
	WindowEnd       time.Time
	PeerKind        int32
	PeerKey         string
	PeerLabels      []byte
	SrcAddress      string
	DstAddress      string
	DstPort         int32
	Protocol        int32
	Direction       int32
	Decision        int32
	MatchedRuleID   string
	ConnectionCount int64
	ByteCount       int64
	FirstSeen       time.Time
	LastSeen        time.Time
	ProcessName     string
}

const listFlowTotals = `-- name: ListFlowTotals :many
SELECT region_id, workload_id, peer_kind, peer_key, peer_labels, dst_port, protocol, direction, decision, matched_rule_id, first_seen, last_seen, connection_count, byte_count, window_count FROM flow_totals
WHERE workload_id = $1
  AND ($2::integer = 0 OR decision = $2::integer)
ORDER BY last_seen DESC, peer_kind, peer_key, dst_port, protocol, decision
`

type ListFlowTotalsParams struct {
	WorkloadID uuid.UUID
	Decision   int32
}

func (q *Queries) ListFlowTotals(ctx context.Context, arg ListFlowTotalsParams) ([]FlowTotal, error) {
	rows, err := q.db.Query(ctx, listFlowTotals, arg.WorkloadID, arg.Decision)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FlowTotal{}
	for rows.Next() {
		var i FlowTotal
		if err := rows.Scan(
			&i.RegionID,
			&i.WorkloadID,
			&i.PeerKind,
			&i.PeerKey,
			&i.PeerLabels,
			&i.DstPort,
			&i.Protocol,
			&i.Direction,
			&i.Decision,
			&i.MatchedRuleID,
			&i.FirstSeen,
			&i.LastSeen,
			&i.ConnectionCount,
			&i.ByteCount,
			&i.WindowCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlowWindows = `-- name: ListFlowWindows :many
SELECT id, region_id, workload_id, window_start, window_end, peer_kind, peer_key, peer_labels, src_address, dst_address, dst_port, protocol, direction, decision, matched_rule_id, connection_count, byte_count, first_seen, last_seen, process_name FROM flow_windows
WHERE workload_id = $1
  AND window_start >= $2
  AND window_start < $3
  AND ($4::integer = 0 OR decision = $4::integer)
ORDER BY window_start DESC, id DESC
LIMIT $5
`

type ListFlowWindowsParams struct {
	WorkloadID uuid.UUID
	Since      time.Time
	Until      time.Time
	Decision   int32
	RowLimit   int32
}

func (q *Queries) ListFlowWindows(ctx context.Context, arg ListFlowWindowsParams) ([]FlowWindow, error) {
	rows, err := q.db.Query(ctx, listFlowWindows,
		arg.WorkloadID,
		arg.Since,
		arg.Until,
		arg.Decision,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FlowWindow{}
	for rows.Next() {
		var i FlowWindow
		if err := rows.Scan(
			&i.ID,
			&i.RegionID,
			&i.WorkloadID,
			&i.WindowStart,
			&i.WindowEnd,
			&i.PeerKind,
			&i.PeerKey,
			&i.PeerLabels,
			&i.SrcAddress,
			&i.DstAddress,
			&i.DstPort,
			&i.Protocol,
			&i.Direction,
			&i.Decision,
			&i.MatchedRuleID,
			&i.ConnectionCount,
			&i.ByteCount,
			&i.FirstSeen,
			&i.LastSeen,
			&i.ProcessName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rollupFlowWindows = `-- name: RollupFlowWindows :many
SELECT peer_kind, peer_key, dst_port, protocol, decision,
       count(DISTINCT workload_id)::bigint AS workload_count,
       sum(connection_count)::bigint       AS connection_count,
       sum(byte_count)::bigint             AS byte_count,
       min(first_seen)::timestamptz        AS first_seen,
       max(last_seen)::timestamptz         AS last_seen
FROM flow_windows
WHERE workload_id = ANY($1::uuid[])
  AND window_start >= $2
  AND window_start < $3
  AND ($4::integer = 0 OR decision = $4::integer)
GROUP BY peer_kind, peer_key, dst_port, protocol, decision
ORDER BY connection_count DESC, peer_kind, peer_key, dst_port, protocol, decision
`

type RollupFlowWindowsParams struct {
	WorkloadIds []uuid.UUID
	Since       time.Time
	Until       time.Time
	Decision    int32
}

type RollupFlowWindowsRow struct {
	PeerKind        int32
	PeerKey         string
	DstPort         int32
	Protocol        int32
	Decision        int32
	WorkloadCount   int64
	ConnectionCount int64
	ByteCount       int64
	FirstSeen       time.Time
	LastSeen        time.Time
}

// The rollup the operator console issues for a label scope: the scope is
// resolved to workload ids by the caller, and the rows are grouped by
// resolved peer and service (destination port and protocol). A decision of
// 0 means every decision.
func (q *Queries) RollupFlowWindows(ctx context.Context, arg RollupFlowWindowsParams) ([]RollupFlowWindowsRow, error) {
	rows, err := q.db.Query(ctx, rollupFlowWindows,
		arg.WorkloadIds,
		arg.Since,
		arg.Until,
		arg.Decision,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RollupFlowWindowsRow{}
	for rows.Next() {
		var i RollupFlowWindowsRow
		if err := rows.Scan(
			&i.PeerKind,
			&i.PeerKey,
			&i.DstPort,
			&i.Protocol,
			&i.Decision,
			&i.WorkloadCount,
			&i.ConnectionCount,
			&i.ByteCount,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tryAcquireRetentionLock = `-- name: TryAcquireRetentionLock :one
SELECT pg_try_advisory_xact_lock($1::bigint)
`

// Retention runs singly across replicas: whichever replica acquires the
// lock prunes, the others skip this round (ADR-0017).
func (q *Queries) TryAcquireRetentionLock(ctx context.Context, key int64) (bool, error) {
	row := q.db.QueryRow(ctx, tryAcquireRetentionLock, key)
	var pg_try_advisory_xact_lock bool
	err := row.Scan(&pg_try_advisory_xact_lock)
	return pg_try_advisory_xact_lock, err
}
