// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mode_changes.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addModeChangeWorkload = `-- name: AddModeChangeWorkload :exec
INSERT INTO mode_change_workloads (mode_change_id, workload_id, previous_mode)
VALUES ($1, $2, $3)
`

type AddModeChangeWorkloadParams struct {
	ModeChangeID uuid.UUID
	WorkloadID   uuid.UUID
	PreviousMode int32
}

func (q *Queries) AddModeChangeWorkload(ctx context.Context, arg AddModeChangeWorkloadParams) error {
	_, err := q.db.Exec(ctx, addModeChangeWorkload, arg.ModeChangeID, arg.WorkloadID, arg.PreviousMode)
	return err
}

const createModeChange = `-- name: CreateModeChange :exec

INSERT INTO mode_changes (id, created_at, target_mode, selector, expected_match_count, matched, desired_updated)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateModeChangeParams struct {
	ID                 uuid.UUID
	CreatedAt          time.Time
	TargetMode         int32
	Selector           []byte
	ExpectedMatchCount int32
	Matched            int32
	DesiredUpdated     int32
}

// Recorded bulk mode changes (ADR-0007 as amended): the intent as
// submitted, the set it resolved to, and what changed. Written inside the
// render transaction that flips the modes, so the record and the flip are
// one unit.
func (q *Queries) CreateModeChange(ctx context.Context, arg CreateModeChangeParams) error {
	_, err := q.db.Exec(ctx, createModeChange,
		arg.ID,
		arg.CreatedAt,
		arg.TargetMode,
		arg.Selector,
		arg.ExpectedMatchCount,
		arg.Matched,
		arg.DesiredUpdated,
	)
	return err
}

const getModeChange = `-- name: GetModeChange :one
SELECT id, region_id, created_at, target_mode, selector, expected_match_count, matched, desired_updated FROM mode_changes
WHERE id = $1
`

func (q *Queries) GetModeChange(ctx context.Context, id uuid.UUID) (ModeChange, error) {
	row := q.db.QueryRow(ctx, getModeChange, id)
	var i ModeChange
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.CreatedAt,
		&i.TargetMode,
		&i.Selector,
		&i.ExpectedMatchCount,
		&i.Matched,
		&i.DesiredUpdated,
	)
	return i, err
}

const getWorkloadModes = `-- name: GetWorkloadModes :many
SELECT id, mode FROM workloads
WHERE id = ANY($1::uuid[])
ORDER BY id
`

type GetWorkloadModesRow struct {
	ID   uuid.UUID
	Mode int32
}

// The modes of a resolved set before it is flipped, and the flip itself,
// by explicit id: the set was resolved once, in this transaction, and a
// label change committed meanwhile does not move it.
func (q *Queries) GetWorkloadModes(ctx context.Context, workloadIds []uuid.UUID) ([]GetWorkloadModesRow, error) {
	rows, err := q.db.Query(ctx, getWorkloadModes, workloadIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWorkloadModesRow{}
	for rows.Next() {
		var i GetWorkloadModesRow
		if err := rows.Scan(&i.ID, &i.Mode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModeChangeWorkloads = `-- name: ListModeChangeWorkloads :many
SELECT mode_change_id, workload_id, previous_mode FROM mode_change_workloads
WHERE mode_change_id = $1
ORDER BY workload_id
`

func (q *Queries) ListModeChangeWorkloads(ctx context.Context, modeChangeID uuid.UUID) ([]ModeChangeWorkload, error) {
	rows, err := q.db.Query(ctx, listModeChangeWorkloads, modeChangeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModeChangeWorkload{}
	for rows.Next() {
		var i ModeChangeWorkload
		if err := rows.Scan(&i.ModeChangeID, &i.WorkloadID, &i.PreviousMode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWorkloadModes = `-- name: SetWorkloadModes :execrows
UPDATE workloads
SET mode = $1::integer
WHERE id = ANY($2::uuid[]) AND mode <> $1::integer
`

type SetWorkloadModesParams struct {
	Mode        int32
	WorkloadIds []uuid.UUID
}

func (q *Queries) SetWorkloadModes(ctx context.Context, arg SetWorkloadModesParams) (int64, error) {
	result, err := q.db.Exec(ctx, setWorkloadModes, arg.Mode, arg.WorkloadIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
