// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operators.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOperatorSession = `-- name: CreateOperatorSession :exec
INSERT INTO operator_sessions (id_hash, created_at, expires_at)
VALUES ($1, $2, $3)
`

type CreateOperatorSessionParams struct {
	IDHash    []byte
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) CreateOperatorSession(ctx context.Context, arg CreateOperatorSessionParams) error {
	_, err := q.db.Exec(ctx, createOperatorSession, arg.IDHash, arg.CreatedAt, arg.ExpiresAt)
	return err
}

const createOperatorToken = `-- name: CreateOperatorToken :exec
INSERT INTO operator_tokens (id, token_hash, token_prefix, name, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateOperatorTokenParams struct {
	ID          uuid.UUID
	TokenHash   []byte
	TokenPrefix string
	Name        string
	CreatedAt   time.Time
	ExpiresAt   *time.Time
}

func (q *Queries) CreateOperatorToken(ctx context.Context, arg CreateOperatorTokenParams) error {
	_, err := q.db.Exec(ctx, createOperatorToken,
		arg.ID,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.Name,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredOperatorSessions = `-- name: DeleteExpiredOperatorSessions :execrows
DELETE FROM operator_sessions
WHERE expires_at <= $1
`

// Retention: expired sessions are removed on the same schedule as aged
// flow windows (ADR-0019, ADR-0021).
func (q *Queries) DeleteExpiredOperatorSessions(ctx context.Context, now time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredOperatorSessions, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOperatorSession = `-- name: DeleteOperatorSession :execrows
DELETE FROM operator_sessions
WHERE id_hash = $1
`

func (q *Queries) DeleteOperatorSession(ctx context.Context, idHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOperatorSession, idHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOperator = `-- name: GetOperator :one

SELECT id, region_id, password_hash, display_name, created_at, updated_at FROM operators
WHERE id = true
`

// Operator surface (ADR-0021). Passwords are stored as argon2id strings;
// session identifiers and operator tokens only as SHA-256 digests. No query
// here touches a plaintext credential.
func (q *Queries) GetOperator(ctx context.Context) (Operator, error) {
	row := q.db.QueryRow(ctx, getOperator)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOperatorSession = `-- name: GetOperatorSession :one
SELECT id_hash, region_id, created_at, expires_at FROM operator_sessions
WHERE id_hash = $1
`

func (q *Queries) GetOperatorSession(ctx context.Context, idHash []byte) (OperatorSession, error) {
	row := q.db.QueryRow(ctx, getOperatorSession, idHash)
	var i OperatorSession
	err := row.Scan(
		&i.IDHash,
		&i.RegionID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getOperatorToken = `-- name: GetOperatorToken :one
SELECT id, region_id, token_hash, token_prefix, name, created_at, expires_at, revoked_at, last_used_at FROM operator_tokens
WHERE id = $1
`

func (q *Queries) GetOperatorToken(ctx context.Context, id uuid.UUID) (OperatorToken, error) {
	row := q.db.QueryRow(ctx, getOperatorToken, id)
	var i OperatorToken
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Name,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getOperatorTokenByHash = `-- name: GetOperatorTokenByHash :one
SELECT id, region_id, token_hash, token_prefix, name, created_at, expires_at, revoked_at, last_used_at FROM operator_tokens
WHERE token_hash = $1
`

func (q *Queries) GetOperatorTokenByHash(ctx context.Context, tokenHash []byte) (OperatorToken, error) {
	row := q.db.QueryRow(ctx, getOperatorTokenByHash, tokenHash)
	var i OperatorToken
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Name,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listOperatorTokens = `-- name: ListOperatorTokens :many
SELECT id, region_id, token_hash, token_prefix, name, created_at, expires_at, revoked_at, last_used_at FROM operator_tokens
ORDER BY created_at DESC, id
`

func (q *Queries) ListOperatorTokens(ctx context.Context) ([]OperatorToken, error) {
	rows, err := q.db.Query(ctx, listOperatorTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperatorToken{}
	for rows.Next() {
		var i OperatorToken
		if err := rows.Scan(
			&i.ID,
			&i.RegionID,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.Name,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordOperatorTokenUse = `-- name: RecordOperatorTokenUse :exec
UPDATE operator_tokens
SET last_used_at = $2
WHERE id = $1
`

type RecordOperatorTokenUseParams struct {
	ID         uuid.UUID
	LastUsedAt *time.Time
}

func (q *Queries) RecordOperatorTokenUse(ctx context.Context, arg RecordOperatorTokenUseParams) error {
	_, err := q.db.Exec(ctx, recordOperatorTokenUse, arg.ID, arg.LastUsedAt)
	return err
}

const revokeOperatorToken = `-- name: RevokeOperatorToken :execrows
UPDATE operator_tokens
SET revoked_at = $2
WHERE id = $1 AND revoked_at IS NULL
`

type RevokeOperatorTokenParams struct {
	ID        uuid.UUID
	RevokedAt *time.Time
}

func (q *Queries) RevokeOperatorToken(ctx context.Context, arg RevokeOperatorTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeOperatorToken, arg.ID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setOperator = `-- name: SetOperator :one
INSERT INTO operators (password_hash, display_name, created_at, updated_at)
VALUES ($1, $2, $3, $3)
ON CONFLICT (id) DO UPDATE
SET password_hash = EXCLUDED.password_hash,
    display_name = EXCLUDED.display_name,
    updated_at = EXCLUDED.updated_at
RETURNING id, region_id, password_hash, display_name, created_at, updated_at
`

type SetOperatorParams struct {
	PasswordHash string
	DisplayName  *string
	CreatedAt    time.Time
}

func (q *Queries) SetOperator(ctx context.Context, arg SetOperatorParams) (Operator, error) {
	row := q.db.QueryRow(ctx, setOperator, arg.PasswordHash, arg.DisplayName, arg.CreatedAt)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
