// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ping.sql

package db

import (
	"context"
)

const ping = `-- name: Ping :one

SELECT 1::int AS one
`

// Queries are hand-written SQL compiled by sqlc into internal/store/db
// (ADR-0006). One file per concern; every production query lives here.
//
// Ping is a connectivity probe that touches no tables. It exists so the data
// layer is exercised end to end before the first migration lands.
func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var one int32
	err := row.Scan(&one)
	return one, err
}
