// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provisioning_tokens.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addProvisioningTokenLabel = `-- name: AddProvisioningTokenLabel :exec
INSERT INTO provisioning_token_labels (token_id, key, value)
VALUES ($1, $2, $3)
`

type AddProvisioningTokenLabelParams struct {
	TokenID uuid.UUID
	Key     string
	Value   string
}

func (q *Queries) AddProvisioningTokenLabel(ctx context.Context, arg AddProvisioningTokenLabelParams) error {
	_, err := q.db.Exec(ctx, addProvisioningTokenLabel, arg.TokenID, arg.Key, arg.Value)
	return err
}

const createProvisioningToken = `-- name: CreateProvisioningToken :one

INSERT INTO provisioning_tokens (id, token_hash, name, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, region_id, token_hash, name, created_at, expires_at, revoked_at, use_count, last_used_at
`

type CreateProvisioningTokenParams struct {
	ID        uuid.UUID
	TokenHash []byte
	Name      string
	ExpiresAt time.Time
}

// Provisioning tokens (ADR-0016). Only the SHA-256 hash of a token is ever
// stored or looked up; no query here touches plaintext.
func (q *Queries) CreateProvisioningToken(ctx context.Context, arg CreateProvisioningTokenParams) (ProvisioningToken, error) {
	row := q.db.QueryRow(ctx, createProvisioningToken,
		arg.ID,
		arg.TokenHash,
		arg.Name,
		arg.ExpiresAt,
	)
	var i ProvisioningToken
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.TokenHash,
		&i.Name,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UseCount,
		&i.LastUsedAt,
	)
	return i, err
}

const getProvisioningToken = `-- name: GetProvisioningToken :one
SELECT id, region_id, token_hash, name, created_at, expires_at, revoked_at, use_count, last_used_at FROM provisioning_tokens
WHERE id = $1
`

func (q *Queries) GetProvisioningToken(ctx context.Context, id uuid.UUID) (ProvisioningToken, error) {
	row := q.db.QueryRow(ctx, getProvisioningToken, id)
	var i ProvisioningToken
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.TokenHash,
		&i.Name,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UseCount,
		&i.LastUsedAt,
	)
	return i, err
}

const getProvisioningTokenByHash = `-- name: GetProvisioningTokenByHash :one
SELECT id, region_id, token_hash, name, created_at, expires_at, revoked_at, use_count, last_used_at FROM provisioning_tokens
WHERE token_hash = $1
`

func (q *Queries) GetProvisioningTokenByHash(ctx context.Context, tokenHash []byte) (ProvisioningToken, error) {
	row := q.db.QueryRow(ctx, getProvisioningTokenByHash, tokenHash)
	var i ProvisioningToken
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.TokenHash,
		&i.Name,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UseCount,
		&i.LastUsedAt,
	)
	return i, err
}

const listAllProvisioningTokenLabels = `-- name: ListAllProvisioningTokenLabels :many
SELECT token_id, key, value FROM provisioning_token_labels
ORDER BY token_id, key
`

func (q *Queries) ListAllProvisioningTokenLabels(ctx context.Context) ([]ProvisioningTokenLabel, error) {
	rows, err := q.db.Query(ctx, listAllProvisioningTokenLabels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProvisioningTokenLabel{}
	for rows.Next() {
		var i ProvisioningTokenLabel
		if err := rows.Scan(&i.TokenID, &i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvisioningTokenLabels = `-- name: ListProvisioningTokenLabels :many
SELECT token_id, key, value FROM provisioning_token_labels
WHERE token_id = $1
ORDER BY key
`

func (q *Queries) ListProvisioningTokenLabels(ctx context.Context, tokenID uuid.UUID) ([]ProvisioningTokenLabel, error) {
	rows, err := q.db.Query(ctx, listProvisioningTokenLabels, tokenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProvisioningTokenLabel{}
	for rows.Next() {
		var i ProvisioningTokenLabel
		if err := rows.Scan(&i.TokenID, &i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvisioningTokens = `-- name: ListProvisioningTokens :many
SELECT id, region_id, token_hash, name, created_at, expires_at, revoked_at, use_count, last_used_at FROM provisioning_tokens
ORDER BY created_at DESC, id
`

func (q *Queries) ListProvisioningTokens(ctx context.Context) ([]ProvisioningToken, error) {
	rows, err := q.db.Query(ctx, listProvisioningTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProvisioningToken{}
	for rows.Next() {
		var i ProvisioningToken
		if err := rows.Scan(
			&i.ID,
			&i.RegionID,
			&i.TokenHash,
			&i.Name,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.UseCount,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordProvisioningTokenUse = `-- name: RecordProvisioningTokenUse :exec
UPDATE provisioning_tokens
SET use_count = use_count + 1, last_used_at = $2
WHERE id = $1
`

type RecordProvisioningTokenUseParams struct {
	ID         uuid.UUID
	LastUsedAt *time.Time
}

func (q *Queries) RecordProvisioningTokenUse(ctx context.Context, arg RecordProvisioningTokenUseParams) error {
	_, err := q.db.Exec(ctx, recordProvisioningTokenUse, arg.ID, arg.LastUsedAt)
	return err
}

const revokeProvisioningToken = `-- name: RevokeProvisioningToken :execrows
UPDATE provisioning_tokens
SET revoked_at = $2
WHERE id = $1 AND revoked_at IS NULL
`

type RevokeProvisioningTokenParams struct {
	ID        uuid.UUID
	RevokedAt *time.Time
}

func (q *Queries) RevokeProvisioningToken(ctx context.Context, arg RevokeProvisioningTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeProvisioningToken, arg.ID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
