// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// Queries are hand-written SQL compiled by sqlc into internal/store/db
	// (ADR-0006). One file per concern; every production query lives here.
	//
	// Ping is a connectivity probe that touches no tables. It exists so the data
	// layer is exercised end to end before the first migration lands.
	Ping(ctx context.Context) (int32, error)
}

var _ Querier = (*Queries)(nil)
