// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	// Rendered per-workload policy and its version (ADR-0018). The render
	// transaction holds an advisory lock so that two renders never interleave
	// their version bumps, and it notifies listeners of every changed workload
	// on commit so that the replica holding the workload's stream pushes the
	// change without anything polling (ADR-0002).
	AcquireRenderLock(ctx context.Context, key int64) error
	AddAddressGroupCIDR(ctx context.Context, arg AddAddressGroupCIDRParams) error
	AddProvisioningTokenLabel(ctx context.Context, arg AddProvisioningTokenLabelParams) error
	AddRule(ctx context.Context, arg AddRuleParams) error
	AddRulePeer(ctx context.Context, arg AddRulePeerParams) error
	AddRulePeerMatch(ctx context.Context, arg AddRulePeerMatchParams) error
	AddRuleServiceEntry(ctx context.Context, arg AddRuleServiceEntryParams) error
	AddRuleServiceRef(ctx context.Context, arg AddRuleServiceRefParams) error
	AddRulesetScopeMatch(ctx context.Context, arg AddRulesetScopeMatchParams) error
	AddServiceEntry(ctx context.Context, arg AddServiceEntryParams) error
	AddWorkloadAddress(ctx context.Context, arg AddWorkloadAddressParams) error
	AddWorkloadLabel(ctx context.Context, arg AddWorkloadLabelParams) error
	AddWorkloadListeningService(ctx context.Context, arg AddWorkloadListeningServiceParams) error
	CountFlowWindows(ctx context.Context) (int64, error)
	CountRulesReferencingAddressGroup(ctx context.Context, addressGroupID *uuid.UUID) (int64, error)
	CountRulesReferencingService(ctx context.Context, serviceID uuid.UUID) (int64, error)
	// Address groups: named CIDR sets for peers that are not managed workloads
	// (ADR-0018).
	CreateAddressGroup(ctx context.Context, arg CreateAddressGroupParams) error
	CreateOperatorSession(ctx context.Context, arg CreateOperatorSessionParams) error
	CreateOperatorToken(ctx context.Context, arg CreateOperatorTokenParams) error
	// Provisioning tokens (ADR-0016). Only the SHA-256 hash of a token is ever
	// stored or looked up; no query here touches plaintext.
	CreateProvisioningToken(ctx context.Context, arg CreateProvisioningTokenParams) (ProvisioningToken, error)
	// Rulesets and their rules: the authored policy model (ADR-0018). A ruleset
	// is written and replaced as a unit; its child rows are deleted and
	// reinserted inside one transaction on update.
	CreateRuleset(ctx context.Context, arg CreateRulesetParams) error
	// Named service definitions: reusable protocol/port sets (ADR-0018).
	CreateService(ctx context.Context, arg CreateServiceParams) error
	// Workload identity registry (ADR-0016). The id column is the workload_id
	// carried in the credential's URI SAN; labels are assigned at enrollment from
	// the provisioning token's scope and are never read from a certificate.
	CreateWorkload(ctx context.Context, arg CreateWorkloadParams) error
	DeleteAddressGroup(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteAddressGroupCIDRs(ctx context.Context, addressGroupID uuid.UUID) error
	// Retention: expired sessions are removed on the same schedule as aged
	// flow windows (ADR-0019, ADR-0021).
	DeleteExpiredOperatorSessions(ctx context.Context, now time.Time) (int64, error)
	// Retention: one bounded batch of the oldest windows before the horizon.
	// The caller loops until a batch deletes nothing, so no single statement
	// holds locks for the whole backlog (ADR-0019).
	DeleteFlowWindowsBefore(ctx context.Context, arg DeleteFlowWindowsBeforeParams) (int64, error)
	DeleteOperatorSession(ctx context.Context, idHash []byte) (int64, error)
	DeleteRules(ctx context.Context, rulesetID uuid.UUID) error
	DeleteRuleset(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteRulesetScopeMatches(ctx context.Context, rulesetID uuid.UUID) error
	DeleteService(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteServiceEntries(ctx context.Context, serviceID uuid.UUID) error
	DeleteWorkloadAddresses(ctx context.Context, workloadID uuid.UUID) error
	DeleteWorkloadLabels(ctx context.Context, workloadID uuid.UUID) error
	DeleteWorkloadListeningServices(ctx context.Context, workloadID uuid.UUID) error
	GetAddressGroup(ctx context.Context, id uuid.UUID) (AddressGroup, error)
	// Operator surface (ADR-0021). Passwords are stored as argon2id strings;
	// session identifiers and operator tokens only as SHA-256 digests. No query
	// here touches a plaintext credential.
	GetOperator(ctx context.Context) (Operator, error)
	GetOperatorSession(ctx context.Context, idHash []byte) (OperatorSession, error)
	GetOperatorToken(ctx context.Context, id uuid.UUID) (OperatorToken, error)
	GetOperatorTokenByHash(ctx context.Context, tokenHash []byte) (OperatorToken, error)
	GetProvisioningToken(ctx context.Context, id uuid.UUID) (ProvisioningToken, error)
	GetProvisioningTokenByHash(ctx context.Context, tokenHash []byte) (ProvisioningToken, error)
	GetRuleset(ctx context.Context, id uuid.UUID) (Ruleset, error)
	GetService(ctx context.Context, id uuid.UUID) (Service, error)
	GetWorkload(ctx context.Context, id uuid.UUID) (Workload, error)
	GetWorkloadPolicy(ctx context.Context, workloadID uuid.UUID) (WorkloadPolicy, error)
	// One workload with its latest rendered version, for the detail read.
	GetWorkloadWithPolicy(ctx context.Context, id uuid.UUID) (GetWorkloadWithPolicyRow, error)
	// Flow storage (ADR-0009, ADR-0019). These are the only statements that
	// touch flow_windows and flow_totals; every caller goes through the
	// FlowStore interface in internal/flowstore.
	InsertFlowWindows(ctx context.Context, arg []InsertFlowWindowsParams) (int64, error)
	ListAddressGroupCIDRs(ctx context.Context, addressGroupID uuid.UUID) ([]AddressGroupCidr, error)
	ListAddressGroups(ctx context.Context) ([]AddressGroup, error)
	ListAllAddressGroupCIDRs(ctx context.Context) ([]AddressGroupCidr, error)
	ListAllProvisioningTokenLabels(ctx context.Context) ([]ProvisioningTokenLabel, error)
	ListAllRulePeerMatches(ctx context.Context) ([]RulePeerMatch, error)
	ListAllRulePeers(ctx context.Context) ([]RulePeer, error)
	ListAllRuleServiceEntries(ctx context.Context) ([]RuleServiceEntry, error)
	ListAllRuleServiceRefs(ctx context.Context) ([]RuleServiceRef, error)
	ListAllRules(ctx context.Context) ([]Rule, error)
	ListAllRulesetScopeMatches(ctx context.Context) ([]RulesetScopeMatch, error)
	ListAllServiceEntries(ctx context.Context) ([]ServiceEntry, error)
	ListAllWorkloadAddresses(ctx context.Context) ([]WorkloadAddress, error)
	ListAllWorkloadLabels(ctx context.Context) ([]WorkloadLabel, error)
	ListFlowTotals(ctx context.Context, arg ListFlowTotalsParams) ([]FlowTotal, error)
	// One page of a workload's windows, newest first, keyed by
	// (window_start, id) so a page never shifts when new windows land. The
	// first page passes a cursor beyond any row. An empty peer key means every
	// peer; a zero protocol means every service.
	ListFlowWindowPage(ctx context.Context, arg ListFlowWindowPageParams) ([]FlowWindow, error)
	ListFlowWindows(ctx context.Context, arg ListFlowWindowsParams) ([]FlowWindow, error)
	ListOperatorTokens(ctx context.Context) ([]OperatorToken, error)
	ListProvisioningTokenLabels(ctx context.Context, tokenID uuid.UUID) ([]ProvisioningTokenLabel, error)
	ListProvisioningTokens(ctx context.Context) ([]ProvisioningToken, error)
	ListRulesets(ctx context.Context) ([]Ruleset, error)
	ListServiceEntries(ctx context.Context, serviceID uuid.UUID) ([]ServiceEntry, error)
	ListServices(ctx context.Context) ([]Service, error)
	ListWorkloadAddresses(ctx context.Context, workloadID uuid.UUID) ([]string, error)
	ListWorkloadAddressesFor(ctx context.Context, workloadIds []uuid.UUID) ([]WorkloadAddress, error)
	ListWorkloadLabels(ctx context.Context, workloadID uuid.UUID) ([]WorkloadLabel, error)
	// The children of the workloads on one page, fetched once per page.
	ListWorkloadLabelsFor(ctx context.Context, workloadIds []uuid.UUID) ([]WorkloadLabel, error)
	ListWorkloadListeningServices(ctx context.Context, workloadID uuid.UUID) ([]WorkloadListeningService, error)
	ListWorkloadListeningServicesFor(ctx context.Context, workloadIds []uuid.UUID) ([]WorkloadListeningService, error)
	// --- operator read model (ADR-0007 as amended) -------------------------------
	// One page of the fleet in the order the fleet screen shows it: the
	// workloads needing attention first (degraded, then offline, then
	// pending, then synced), most recently seen first within a state, then by
	// id. The cursor is the (rank, last seen, id) of the last row served; the
	// first page passes a rank below every row. A workload never seen sorts
	// as if seen at the epoch. An empty id array means every workload; a zero
	// mode or sync state means any. The latest rendered version rides along
	// from workload_policies so sync drift is one read.
	ListWorkloadPage(ctx context.Context, arg ListWorkloadPageParams) ([]ListWorkloadPageRow, error)
	ListWorkloadPolicies(ctx context.Context) ([]WorkloadPolicy, error)
	// --- inventory and status (ADR-0018) ------------------------------------------
	ListWorkloads(ctx context.Context) ([]Workload, error)
	NotifyPolicyChanged(ctx context.Context, arg NotifyPolicyChangedParams) error
	// Queries are hand-written SQL compiled by sqlc into internal/store/db
	// (ADR-0006). One file per concern; every production query lives here.
	//
	// Ping is a connectivity probe that touches no tables. It exists so the data
	// layer is exercised end to end before the first migration lands.
	Ping(ctx context.Context) (int32, error)
	RecordOperatorTokenUse(ctx context.Context, arg RecordOperatorTokenUseParams) error
	RecordProvisioningTokenUse(ctx context.Context, arg RecordProvisioningTokenUseParams) error
	RecordWorkloadAgent(ctx context.Context, arg RecordWorkloadAgentParams) (int64, error)
	RecordWorkloadApplied(ctx context.Context, arg RecordWorkloadAppliedParams) (int64, error)
	RecordWorkloadHeartbeat(ctx context.Context, arg RecordWorkloadHeartbeatParams) (int64, error)
	RecordWorkloadHeartbeatSeen(ctx context.Context, arg RecordWorkloadHeartbeatSeenParams) (int64, error)
	RecordWorkloadInventory(ctx context.Context, arg RecordWorkloadInventoryParams) (int64, error)
	RecordWorkloadRenewal(ctx context.Context, arg RecordWorkloadRenewalParams) (int64, error)
	RevokeOperatorToken(ctx context.Context, arg RevokeOperatorTokenParams) (int64, error)
	RevokeProvisioningToken(ctx context.Context, arg RevokeProvisioningTokenParams) (int64, error)
	// The rollup the operator console issues for a label scope: the scope is
	// resolved to workload ids by the caller, and the rows are grouped by
	// resolved peer and service (destination port and protocol). A decision of
	// 0 means every decision.
	RollupFlowWindows(ctx context.Context, arg RollupFlowWindowsParams) ([]RollupFlowWindowsRow, error)
	// Grouped by the reporting workload and the service reached on it: the
	// cells of the matrix.
	RollupFlowsByDstService(ctx context.Context, arg RollupFlowsByDstServiceParams) ([]RollupFlowsByDstServiceRow, error)
	// --- operator read model -----------------------------------------------------
	//
	// The rollups the operator surface and the command line issue (ADR-0007 as
	// amended, ADR-0019 decision 4). Each grouping the surface offers is one
	// named statement over the same windows; the caller picks the statement
	// and never assembles one. Every rollup shares one filter convention: an
	// empty workload id array means every workload, a zero decision or
	// direction means any, and a zero protocol means every service (a service
	// is one destination port and protocol). Ordering is by connection count
	// unless order_by is 'recent', in which case the most recently seen group
	// comes first. The window bounds actually covered, the number of groups,
	// and the totals across every group ride on each row as window aggregates,
	// so a truncated result still says how it relates to the whole. The
	// decision-and-time and workload-and-time indexes serve all four.
	// Grouped by the resolved rule that admitted the traffic; records with no
	// matched rule form the group with the empty rule id.
	RollupFlowsByRule(ctx context.Context, arg RollupFlowsByRuleParams) ([]RollupFlowsByRuleRow, error)
	// Grouped by rule and the resolved peer that hit it. The label snapshot
	// of a peer is the one stored with its most recently seen record.
	RollupFlowsByRulePeer(ctx context.Context, arg RollupFlowsByRulePeerParams) ([]RollupFlowsByRulePeerRow, error)
	// Grouped by the resolved source peer and the reporting workload: the
	// edges of the dependency map. Inbound only in this version, so the
	// source is the peer and the destination is the workload.
	RollupFlowsBySrcDst(ctx context.Context, arg RollupFlowsBySrcDstParams) ([]RollupFlowsBySrcDstRow, error)
	SetOperator(ctx context.Context, arg SetOperatorParams) (Operator, error)
	SetWorkloadMode(ctx context.Context, arg SetWorkloadModeParams) (int64, error)
	SetWorkloadSyncState(ctx context.Context, arg SetWorkloadSyncStateParams) (int64, error)
	// Retention runs singly across replicas: whichever replica acquires the
	// lock prunes, the others skip this round (ADR-0017).
	TryAcquireRetentionLock(ctx context.Context, key int64) (bool, error)
	UpdateAddressGroup(ctx context.Context, arg UpdateAddressGroupParams) (int64, error)
	UpdateRuleset(ctx context.Context, arg UpdateRulesetParams) (int64, error)
	UpdateService(ctx context.Context, arg UpdateServiceParams) (int64, error)
	UpsertFlowTotal(ctx context.Context, arg []UpsertFlowTotalParams) *UpsertFlowTotalBatchResults
	UpsertWorkloadPolicy(ctx context.Context, arg UpsertWorkloadPolicyParams) error
}

var _ Querier = (*Queries)(nil)
