// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rulesets.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addRule = `-- name: AddRule :exec
INSERT INTO rules (id, ruleset_id, ordinal, direction, enabled, description, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type AddRuleParams struct {
	ID          uuid.UUID
	RulesetID   uuid.UUID
	Ordinal     int32
	Direction   int32
	Enabled     bool
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) AddRule(ctx context.Context, arg AddRuleParams) error {
	_, err := q.db.Exec(ctx, addRule,
		arg.ID,
		arg.RulesetID,
		arg.Ordinal,
		arg.Direction,
		arg.Enabled,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const addRulePeer = `-- name: AddRulePeer :exec
INSERT INTO rule_peers (rule_id, ordinal, kind, address_group_id, cidr)
VALUES ($1, $2, $3, $4, $5)
`

type AddRulePeerParams struct {
	RuleID         uuid.UUID
	Ordinal        int32
	Kind           int32
	AddressGroupID *uuid.UUID
	Cidr           *string
}

func (q *Queries) AddRulePeer(ctx context.Context, arg AddRulePeerParams) error {
	_, err := q.db.Exec(ctx, addRulePeer,
		arg.RuleID,
		arg.Ordinal,
		arg.Kind,
		arg.AddressGroupID,
		arg.Cidr,
	)
	return err
}

const addRulePeerMatch = `-- name: AddRulePeerMatch :exec
INSERT INTO rule_peer_matches (rule_id, peer_ordinal, key, "values")
VALUES ($1, $2, $3, $4)
`

type AddRulePeerMatchParams struct {
	RuleID      uuid.UUID
	PeerOrdinal int32
	Key         string
	Values      []string
}

func (q *Queries) AddRulePeerMatch(ctx context.Context, arg AddRulePeerMatchParams) error {
	_, err := q.db.Exec(ctx, addRulePeerMatch,
		arg.RuleID,
		arg.PeerOrdinal,
		arg.Key,
		arg.Values,
	)
	return err
}

const addRuleServiceEntry = `-- name: AddRuleServiceEntry :exec
INSERT INTO rule_service_entries (rule_id, ordinal, protocol, port_start, port_end)
VALUES ($1, $2, $3, $4, $5)
`

type AddRuleServiceEntryParams struct {
	RuleID    uuid.UUID
	Ordinal   int32
	Protocol  int32
	PortStart *int32
	PortEnd   *int32
}

func (q *Queries) AddRuleServiceEntry(ctx context.Context, arg AddRuleServiceEntryParams) error {
	_, err := q.db.Exec(ctx, addRuleServiceEntry,
		arg.RuleID,
		arg.Ordinal,
		arg.Protocol,
		arg.PortStart,
		arg.PortEnd,
	)
	return err
}

const addRuleServiceRef = `-- name: AddRuleServiceRef :exec
INSERT INTO rule_service_refs (rule_id, service_id)
VALUES ($1, $2)
`

type AddRuleServiceRefParams struct {
	RuleID    uuid.UUID
	ServiceID uuid.UUID
}

func (q *Queries) AddRuleServiceRef(ctx context.Context, arg AddRuleServiceRefParams) error {
	_, err := q.db.Exec(ctx, addRuleServiceRef, arg.RuleID, arg.ServiceID)
	return err
}

const addRulesetScopeMatch = `-- name: AddRulesetScopeMatch :exec
INSERT INTO ruleset_scope_matches (ruleset_id, key, "values")
VALUES ($1, $2, $3)
`

type AddRulesetScopeMatchParams struct {
	RulesetID uuid.UUID
	Key       string
	Values    []string
}

func (q *Queries) AddRulesetScopeMatch(ctx context.Context, arg AddRulesetScopeMatchParams) error {
	_, err := q.db.Exec(ctx, addRulesetScopeMatch, arg.RulesetID, arg.Key, arg.Values)
	return err
}

const createRuleset = `-- name: CreateRuleset :exec

INSERT INTO rulesets (id, name, description, enabled, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $5)
`

type CreateRulesetParams struct {
	ID          uuid.UUID
	Name        string
	Description string
	Enabled     bool
	CreatedAt   time.Time
}

// Rulesets and their rules: the authored policy model (ADR-0018). A ruleset
// is written and replaced as a unit; its child rows are deleted and
// reinserted inside one transaction on update.
func (q *Queries) CreateRuleset(ctx context.Context, arg CreateRulesetParams) error {
	_, err := q.db.Exec(ctx, createRuleset,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Enabled,
		arg.CreatedAt,
	)
	return err
}

const deleteRules = `-- name: DeleteRules :exec
DELETE FROM rules
WHERE ruleset_id = $1
`

func (q *Queries) DeleteRules(ctx context.Context, rulesetID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRules, rulesetID)
	return err
}

const deleteRuleset = `-- name: DeleteRuleset :execrows
DELETE FROM rulesets
WHERE id = $1 AND ($2::timestamptz IS NULL OR updated_at = $2::timestamptz)
`

type DeleteRulesetParams struct {
	ID       uuid.UUID
	Expected *time.Time
}

func (q *Queries) DeleteRuleset(ctx context.Context, arg DeleteRulesetParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRuleset, arg.ID, arg.Expected)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRulesetScopeMatches = `-- name: DeleteRulesetScopeMatches :exec
DELETE FROM ruleset_scope_matches
WHERE ruleset_id = $1
`

func (q *Queries) DeleteRulesetScopeMatches(ctx context.Context, rulesetID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRulesetScopeMatches, rulesetID)
	return err
}

const getRuleset = `-- name: GetRuleset :one
SELECT id, region_id, name, description, enabled, created_at, updated_at FROM rulesets
WHERE id = $1
`

func (q *Queries) GetRuleset(ctx context.Context, id uuid.UUID) (Ruleset, error) {
	row := q.db.QueryRow(ctx, getRuleset, id)
	var i Ruleset
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllRulePeerMatches = `-- name: ListAllRulePeerMatches :many
SELECT rule_id, peer_ordinal, key, values FROM rule_peer_matches
ORDER BY rule_id, peer_ordinal, key
`

func (q *Queries) ListAllRulePeerMatches(ctx context.Context) ([]RulePeerMatch, error) {
	rows, err := q.db.Query(ctx, listAllRulePeerMatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RulePeerMatch{}
	for rows.Next() {
		var i RulePeerMatch
		if err := rows.Scan(
			&i.RuleID,
			&i.PeerOrdinal,
			&i.Key,
			&i.Values,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllRulePeers = `-- name: ListAllRulePeers :many
SELECT rule_id, ordinal, kind, address_group_id, cidr FROM rule_peers
ORDER BY rule_id, ordinal
`

func (q *Queries) ListAllRulePeers(ctx context.Context) ([]RulePeer, error) {
	rows, err := q.db.Query(ctx, listAllRulePeers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RulePeer{}
	for rows.Next() {
		var i RulePeer
		if err := rows.Scan(
			&i.RuleID,
			&i.Ordinal,
			&i.Kind,
			&i.AddressGroupID,
			&i.Cidr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllRuleServiceEntries = `-- name: ListAllRuleServiceEntries :many
SELECT rule_id, ordinal, protocol, port_start, port_end FROM rule_service_entries
ORDER BY rule_id, ordinal
`

func (q *Queries) ListAllRuleServiceEntries(ctx context.Context) ([]RuleServiceEntry, error) {
	rows, err := q.db.Query(ctx, listAllRuleServiceEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RuleServiceEntry{}
	for rows.Next() {
		var i RuleServiceEntry
		if err := rows.Scan(
			&i.RuleID,
			&i.Ordinal,
			&i.Protocol,
			&i.PortStart,
			&i.PortEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllRuleServiceRefs = `-- name: ListAllRuleServiceRefs :many
SELECT rule_id, service_id FROM rule_service_refs
ORDER BY rule_id, service_id
`

func (q *Queries) ListAllRuleServiceRefs(ctx context.Context) ([]RuleServiceRef, error) {
	rows, err := q.db.Query(ctx, listAllRuleServiceRefs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RuleServiceRef{}
	for rows.Next() {
		var i RuleServiceRef
		if err := rows.Scan(&i.RuleID, &i.ServiceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllRules = `-- name: ListAllRules :many
SELECT id, ruleset_id, ordinal, direction, enabled, description, created_at, updated_at FROM rules
ORDER BY ruleset_id, ordinal
`

func (q *Queries) ListAllRules(ctx context.Context) ([]Rule, error) {
	rows, err := q.db.Query(ctx, listAllRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rule{}
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.RulesetID,
			&i.Ordinal,
			&i.Direction,
			&i.Enabled,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllRulesetScopeMatches = `-- name: ListAllRulesetScopeMatches :many
SELECT ruleset_id, key, values FROM ruleset_scope_matches
ORDER BY ruleset_id, key
`

func (q *Queries) ListAllRulesetScopeMatches(ctx context.Context) ([]RulesetScopeMatch, error) {
	rows, err := q.db.Query(ctx, listAllRulesetScopeMatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RulesetScopeMatch{}
	for rows.Next() {
		var i RulesetScopeMatch
		if err := rows.Scan(&i.RulesetID, &i.Key, &i.Values); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRulesets = `-- name: ListRulesets :many
SELECT id, region_id, name, description, enabled, created_at, updated_at FROM rulesets
ORDER BY name, id
`

func (q *Queries) ListRulesets(ctx context.Context) ([]Ruleset, error) {
	rows, err := q.db.Query(ctx, listRulesets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ruleset{}
	for rows.Next() {
		var i Ruleset
		if err := rows.Scan(
			&i.ID,
			&i.RegionID,
			&i.Name,
			&i.Description,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRuleset = `-- name: UpdateRuleset :execrows
UPDATE rulesets
SET name = $2, description = $3, enabled = $4, updated_at = $5
WHERE id = $1 AND ($6::timestamptz IS NULL OR updated_at = $6::timestamptz)
`

type UpdateRulesetParams struct {
	ID          uuid.UUID
	Name        string
	Description string
	Enabled     bool
	UpdatedAt   time.Time
	Expected    *time.Time
}

// A conditional write: expected is the updated_at the caller last read,
// or NULL for an unconditional write (the command line's default). Zero
// rows with a NULL expected means the ruleset does not exist; zero rows
// with one set means either that or a version the caller did not see.
func (q *Queries) UpdateRuleset(ctx context.Context, arg UpdateRulesetParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRuleset,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Enabled,
		arg.UpdatedAt,
		arg.Expected,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
