// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addServiceEntry = `-- name: AddServiceEntry :exec
INSERT INTO service_entries (service_id, ordinal, protocol, port_start, port_end)
VALUES ($1, $2, $3, $4, $5)
`

type AddServiceEntryParams struct {
	ServiceID uuid.UUID
	Ordinal   int32
	Protocol  int32
	PortStart *int32
	PortEnd   *int32
}

func (q *Queries) AddServiceEntry(ctx context.Context, arg AddServiceEntryParams) error {
	_, err := q.db.Exec(ctx, addServiceEntry,
		arg.ServiceID,
		arg.Ordinal,
		arg.Protocol,
		arg.PortStart,
		arg.PortEnd,
	)
	return err
}

const countRulesReferencingService = `-- name: CountRulesReferencingService :one
SELECT count(*) FROM rule_service_refs
WHERE service_id = $1
`

func (q *Queries) CountRulesReferencingService(ctx context.Context, serviceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRulesReferencingService, serviceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createService = `-- name: CreateService :exec

INSERT INTO services (id, name, created_at, updated_at)
VALUES ($1, $2, $3, $3)
`

type CreateServiceParams struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

// Named service definitions: reusable protocol/port sets (ADR-0018).
func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) error {
	_, err := q.db.Exec(ctx, createService, arg.ID, arg.Name, arg.CreatedAt)
	return err
}

const deleteService = `-- name: DeleteService :execrows
DELETE FROM services
WHERE id = $1 AND ($2::text IS NULL OR version::text = $2::text)
`

type DeleteServiceParams struct {
	ID       uuid.UUID
	Expected *string
}

func (q *Queries) DeleteService(ctx context.Context, arg DeleteServiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteService, arg.ID, arg.Expected)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteServiceEntries = `-- name: DeleteServiceEntries :exec
DELETE FROM service_entries
WHERE service_id = $1
`

func (q *Queries) DeleteServiceEntries(ctx context.Context, serviceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteServiceEntries, serviceID)
	return err
}

const getService = `-- name: GetService :one
SELECT id, region_id, name, created_at, updated_at, version FROM services
WHERE id = $1
`

func (q *Queries) GetService(ctx context.Context, id uuid.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const listAllServiceEntries = `-- name: ListAllServiceEntries :many
SELECT service_id, ordinal, protocol, port_start, port_end FROM service_entries
ORDER BY service_id, ordinal
`

func (q *Queries) ListAllServiceEntries(ctx context.Context) ([]ServiceEntry, error) {
	rows, err := q.db.Query(ctx, listAllServiceEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceEntry{}
	for rows.Next() {
		var i ServiceEntry
		if err := rows.Scan(
			&i.ServiceID,
			&i.Ordinal,
			&i.Protocol,
			&i.PortStart,
			&i.PortEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceEntries = `-- name: ListServiceEntries :many
SELECT service_id, ordinal, protocol, port_start, port_end FROM service_entries
WHERE service_id = $1
ORDER BY ordinal
`

func (q *Queries) ListServiceEntries(ctx context.Context, serviceID uuid.UUID) ([]ServiceEntry, error) {
	rows, err := q.db.Query(ctx, listServiceEntries, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceEntry{}
	for rows.Next() {
		var i ServiceEntry
		if err := rows.Scan(
			&i.ServiceID,
			&i.Ordinal,
			&i.Protocol,
			&i.PortStart,
			&i.PortEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServices = `-- name: ListServices :many
SELECT id, region_id, name, created_at, updated_at, version FROM services
ORDER BY name, id
`

func (q *Queries) ListServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.RegionID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET name = $2, updated_at = $3, version = version + 1
WHERE id = $1 AND ($4::text IS NULL OR version::text = $4::text)
RETURNING version
`

type UpdateServiceParams struct {
	ID        uuid.UUID
	Name      string
	UpdatedAt time.Time
	Expected  *string
}

// Conditional writes: expected is the version token the caller last read,
// compared byte-exact against the stored version's decimal form, or NULL
// for an unconditional write. Every write advances the version by one.
func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ID,
		arg.Name,
		arg.UpdatedAt,
		arg.Expected,
	)
	var version int64
	err := row.Scan(&version)
	return version, err
}
