// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workload_policies.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acquireRenderLock = `-- name: AcquireRenderLock :exec

SELECT pg_advisory_xact_lock($1::bigint)
`

// Rendered per-workload policy and its version (ADR-0018). The render
// transaction holds an advisory lock so that two renders never interleave
// their version bumps, and it notifies listeners of every changed workload
// on commit so that the replica holding the workload's stream pushes the
// change without anything polling (ADR-0002).
func (q *Queries) AcquireRenderLock(ctx context.Context, key int64) error {
	_, err := q.db.Exec(ctx, acquireRenderLock, key)
	return err
}

const getWorkloadPolicy = `-- name: GetWorkloadPolicy :one
SELECT workload_id, version, policy, rendered_at FROM workload_policies
WHERE workload_id = $1
`

func (q *Queries) GetWorkloadPolicy(ctx context.Context, workloadID uuid.UUID) (WorkloadPolicy, error) {
	row := q.db.QueryRow(ctx, getWorkloadPolicy, workloadID)
	var i WorkloadPolicy
	err := row.Scan(
		&i.WorkloadID,
		&i.Version,
		&i.Policy,
		&i.RenderedAt,
	)
	return i, err
}

const listWorkloadPolicies = `-- name: ListWorkloadPolicies :many
SELECT workload_id, version, policy, rendered_at FROM workload_policies
ORDER BY workload_id
`

func (q *Queries) ListWorkloadPolicies(ctx context.Context) ([]WorkloadPolicy, error) {
	rows, err := q.db.Query(ctx, listWorkloadPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkloadPolicy{}
	for rows.Next() {
		var i WorkloadPolicy
		if err := rows.Scan(
			&i.WorkloadID,
			&i.Version,
			&i.Policy,
			&i.RenderedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notifyPolicyChanged = `-- name: NotifyPolicyChanged :exec
SELECT pg_notify($1::text, $2::text)
`

type NotifyPolicyChangedParams struct {
	Channel string
	Payload string
}

func (q *Queries) NotifyPolicyChanged(ctx context.Context, arg NotifyPolicyChangedParams) error {
	_, err := q.db.Exec(ctx, notifyPolicyChanged, arg.Channel, arg.Payload)
	return err
}

const upsertWorkloadPolicy = `-- name: UpsertWorkloadPolicy :exec
INSERT INTO workload_policies (workload_id, version, policy, rendered_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (workload_id) DO UPDATE
SET version = EXCLUDED.version, policy = EXCLUDED.policy, rendered_at = EXCLUDED.rendered_at
`

type UpsertWorkloadPolicyParams struct {
	WorkloadID uuid.UUID
	Version    int64
	Policy     []byte
	RenderedAt time.Time
}

func (q *Queries) UpsertWorkloadPolicy(ctx context.Context, arg UpsertWorkloadPolicyParams) error {
	_, err := q.db.Exec(ctx, upsertWorkloadPolicy,
		arg.WorkloadID,
		arg.Version,
		arg.Policy,
		arg.RenderedAt,
	)
	return err
}
