// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workloads.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addWorkloadAddress = `-- name: AddWorkloadAddress :exec
INSERT INTO workload_addresses (workload_id, address)
VALUES ($1, $2)
`

type AddWorkloadAddressParams struct {
	WorkloadID uuid.UUID
	Address    string
}

func (q *Queries) AddWorkloadAddress(ctx context.Context, arg AddWorkloadAddressParams) error {
	_, err := q.db.Exec(ctx, addWorkloadAddress, arg.WorkloadID, arg.Address)
	return err
}

const addWorkloadLabel = `-- name: AddWorkloadLabel :exec
INSERT INTO workload_labels (workload_id, key, value)
VALUES ($1, $2, $3)
`

type AddWorkloadLabelParams struct {
	WorkloadID uuid.UUID
	Key        string
	Value      string
}

func (q *Queries) AddWorkloadLabel(ctx context.Context, arg AddWorkloadLabelParams) error {
	_, err := q.db.Exec(ctx, addWorkloadLabel, arg.WorkloadID, arg.Key, arg.Value)
	return err
}

const addWorkloadListeningService = `-- name: AddWorkloadListeningService :exec
INSERT INTO workload_listening_services (workload_id, protocol, port, process_name, process_path)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (workload_id, protocol, port) DO UPDATE
SET process_name = EXCLUDED.process_name, process_path = EXCLUDED.process_path
`

type AddWorkloadListeningServiceParams struct {
	WorkloadID  uuid.UUID
	Protocol    int32
	Port        int32
	ProcessName string
	ProcessPath string
}

func (q *Queries) AddWorkloadListeningService(ctx context.Context, arg AddWorkloadListeningServiceParams) error {
	_, err := q.db.Exec(ctx, addWorkloadListeningService,
		arg.WorkloadID,
		arg.Protocol,
		arg.Port,
		arg.ProcessName,
		arg.ProcessPath,
	)
	return err
}

const createWorkload = `-- name: CreateWorkload :exec

INSERT INTO workloads (id, provisioning_token_id, hostname, enrolled_at, credential_serial, credential_expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateWorkloadParams struct {
	ID                  uuid.UUID
	ProvisioningTokenID uuid.UUID
	Hostname            string
	EnrolledAt          time.Time
	CredentialSerial    string
	CredentialExpiresAt time.Time
}

// Workload identity registry (ADR-0016). The id column is the workload_id
// carried in the credential's URI SAN; labels are assigned at enrollment from
// the provisioning token's scope and are never read from a certificate.
func (q *Queries) CreateWorkload(ctx context.Context, arg CreateWorkloadParams) error {
	_, err := q.db.Exec(ctx, createWorkload,
		arg.ID,
		arg.ProvisioningTokenID,
		arg.Hostname,
		arg.EnrolledAt,
		arg.CredentialSerial,
		arg.CredentialExpiresAt,
	)
	return err
}

const deleteWorkloadAddresses = `-- name: DeleteWorkloadAddresses :exec
DELETE FROM workload_addresses
WHERE workload_id = $1
`

func (q *Queries) DeleteWorkloadAddresses(ctx context.Context, workloadID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkloadAddresses, workloadID)
	return err
}

const deleteWorkloadLabels = `-- name: DeleteWorkloadLabels :exec
DELETE FROM workload_labels
WHERE workload_id = $1
`

func (q *Queries) DeleteWorkloadLabels(ctx context.Context, workloadID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkloadLabels, workloadID)
	return err
}

const deleteWorkloadListeningServices = `-- name: DeleteWorkloadListeningServices :exec
DELETE FROM workload_listening_services
WHERE workload_id = $1
`

func (q *Queries) DeleteWorkloadListeningServices(ctx context.Context, workloadID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkloadListeningServices, workloadID)
	return err
}

const getWorkload = `-- name: GetWorkload :one
SELECT id, region_id, provisioning_token_id, hostname, enrolled_at, credential_serial, credential_expires_at, last_renewed_at, mode, facts, agent_version, agent_capabilities, last_seen_at, sync_state, applied_policy_version, sync_error, dropped_flow_records, credential_renewal_error, last_snapshot_sent_at, last_acked_at, last_apply_failed_at FROM workloads
WHERE id = $1
`

func (q *Queries) GetWorkload(ctx context.Context, id uuid.UUID) (Workload, error) {
	row := q.db.QueryRow(ctx, getWorkload, id)
	var i Workload
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.ProvisioningTokenID,
		&i.Hostname,
		&i.EnrolledAt,
		&i.CredentialSerial,
		&i.CredentialExpiresAt,
		&i.LastRenewedAt,
		&i.Mode,
		&i.Facts,
		&i.AgentVersion,
		&i.AgentCapabilities,
		&i.LastSeenAt,
		&i.SyncState,
		&i.AppliedPolicyVersion,
		&i.SyncError,
		&i.DroppedFlowRecords,
		&i.CredentialRenewalError,
		&i.LastSnapshotSentAt,
		&i.LastAckedAt,
		&i.LastApplyFailedAt,
	)
	return i, err
}

const getWorkloadWithPolicy = `-- name: GetWorkloadWithPolicy :one
SELECT w.id, w.region_id, w.provisioning_token_id, w.hostname, w.enrolled_at, w.credential_serial, w.credential_expires_at, w.last_renewed_at, w.mode, w.facts, w.agent_version, w.agent_capabilities, w.last_seen_at, w.sync_state, w.applied_policy_version, w.sync_error, w.dropped_flow_records, w.credential_renewal_error, w.last_snapshot_sent_at, w.last_acked_at, w.last_apply_failed_at, p.version AS latest_version, p.rendered_at AS latest_rendered_at
FROM workloads w
LEFT JOIN workload_policies p ON p.workload_id = w.id
WHERE w.id = $1
`

type GetWorkloadWithPolicyRow struct {
	Workload         Workload
	LatestVersion    pgtype.Int8
	LatestRenderedAt *time.Time
}

// One workload with its latest rendered version, for the detail read.
func (q *Queries) GetWorkloadWithPolicy(ctx context.Context, id uuid.UUID) (GetWorkloadWithPolicyRow, error) {
	row := q.db.QueryRow(ctx, getWorkloadWithPolicy, id)
	var i GetWorkloadWithPolicyRow
	err := row.Scan(
		&i.Workload.ID,
		&i.Workload.RegionID,
		&i.Workload.ProvisioningTokenID,
		&i.Workload.Hostname,
		&i.Workload.EnrolledAt,
		&i.Workload.CredentialSerial,
		&i.Workload.CredentialExpiresAt,
		&i.Workload.LastRenewedAt,
		&i.Workload.Mode,
		&i.Workload.Facts,
		&i.Workload.AgentVersion,
		&i.Workload.AgentCapabilities,
		&i.Workload.LastSeenAt,
		&i.Workload.SyncState,
		&i.Workload.AppliedPolicyVersion,
		&i.Workload.SyncError,
		&i.Workload.DroppedFlowRecords,
		&i.Workload.CredentialRenewalError,
		&i.Workload.LastSnapshotSentAt,
		&i.Workload.LastAckedAt,
		&i.Workload.LastApplyFailedAt,
		&i.LatestVersion,
		&i.LatestRenderedAt,
	)
	return i, err
}

const listAllWorkloadAddresses = `-- name: ListAllWorkloadAddresses :many
SELECT workload_id, address FROM workload_addresses
ORDER BY workload_id, address
`

func (q *Queries) ListAllWorkloadAddresses(ctx context.Context) ([]WorkloadAddress, error) {
	rows, err := q.db.Query(ctx, listAllWorkloadAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkloadAddress{}
	for rows.Next() {
		var i WorkloadAddress
		if err := rows.Scan(&i.WorkloadID, &i.Address); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllWorkloadLabels = `-- name: ListAllWorkloadLabels :many
SELECT workload_id, key, value FROM workload_labels
ORDER BY workload_id, key
`

func (q *Queries) ListAllWorkloadLabels(ctx context.Context) ([]WorkloadLabel, error) {
	rows, err := q.db.Query(ctx, listAllWorkloadLabels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkloadLabel{}
	for rows.Next() {
		var i WorkloadLabel
		if err := rows.Scan(&i.WorkloadID, &i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkloadAddresses = `-- name: ListWorkloadAddresses :many
SELECT address FROM workload_addresses
WHERE workload_id = $1
ORDER BY address
`

func (q *Queries) ListWorkloadAddresses(ctx context.Context, workloadID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listWorkloadAddresses, workloadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var address string
		if err := rows.Scan(&address); err != nil {
			return nil, err
		}
		items = append(items, address)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkloadAddressesFor = `-- name: ListWorkloadAddressesFor :many
SELECT workload_id, address FROM workload_addresses
WHERE workload_id = ANY($1::uuid[])
ORDER BY workload_id, address
`

func (q *Queries) ListWorkloadAddressesFor(ctx context.Context, workloadIds []uuid.UUID) ([]WorkloadAddress, error) {
	rows, err := q.db.Query(ctx, listWorkloadAddressesFor, workloadIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkloadAddress{}
	for rows.Next() {
		var i WorkloadAddress
		if err := rows.Scan(&i.WorkloadID, &i.Address); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkloadLabels = `-- name: ListWorkloadLabels :many
SELECT workload_id, key, value FROM workload_labels
WHERE workload_id = $1
ORDER BY key
`

func (q *Queries) ListWorkloadLabels(ctx context.Context, workloadID uuid.UUID) ([]WorkloadLabel, error) {
	rows, err := q.db.Query(ctx, listWorkloadLabels, workloadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkloadLabel{}
	for rows.Next() {
		var i WorkloadLabel
		if err := rows.Scan(&i.WorkloadID, &i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkloadLabelsFor = `-- name: ListWorkloadLabelsFor :many
SELECT workload_id, key, value FROM workload_labels
WHERE workload_id = ANY($1::uuid[])
ORDER BY workload_id, key
`

// The children of the workloads on one page, fetched once per page.
func (q *Queries) ListWorkloadLabelsFor(ctx context.Context, workloadIds []uuid.UUID) ([]WorkloadLabel, error) {
	rows, err := q.db.Query(ctx, listWorkloadLabelsFor, workloadIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkloadLabel{}
	for rows.Next() {
		var i WorkloadLabel
		if err := rows.Scan(&i.WorkloadID, &i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkloadListeningServices = `-- name: ListWorkloadListeningServices :many
SELECT workload_id, protocol, port, process_name, process_path FROM workload_listening_services
WHERE workload_id = $1
ORDER BY protocol, port
`

func (q *Queries) ListWorkloadListeningServices(ctx context.Context, workloadID uuid.UUID) ([]WorkloadListeningService, error) {
	rows, err := q.db.Query(ctx, listWorkloadListeningServices, workloadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkloadListeningService{}
	for rows.Next() {
		var i WorkloadListeningService
		if err := rows.Scan(
			&i.WorkloadID,
			&i.Protocol,
			&i.Port,
			&i.ProcessName,
			&i.ProcessPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkloadListeningServicesFor = `-- name: ListWorkloadListeningServicesFor :many
SELECT workload_id, protocol, port, process_name, process_path FROM workload_listening_services
WHERE workload_id = ANY($1::uuid[])
ORDER BY workload_id, protocol, port
`

func (q *Queries) ListWorkloadListeningServicesFor(ctx context.Context, workloadIds []uuid.UUID) ([]WorkloadListeningService, error) {
	rows, err := q.db.Query(ctx, listWorkloadListeningServicesFor, workloadIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkloadListeningService{}
	for rows.Next() {
		var i WorkloadListeningService
		if err := rows.Scan(
			&i.WorkloadID,
			&i.Protocol,
			&i.Port,
			&i.ProcessName,
			&i.ProcessPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkloadPage = `-- name: ListWorkloadPage :many

SELECT w.id, w.region_id, w.provisioning_token_id, w.hostname, w.enrolled_at,
       w.credential_serial, w.credential_expires_at, w.last_renewed_at,
       w.mode, w.facts, w.agent_version, w.agent_capabilities, w.last_seen_at,
       w.sync_state, w.applied_policy_version, w.sync_error, w.dropped_flow_records,
       w.credential_renewal_error, w.last_snapshot_sent_at, w.last_acked_at, w.last_apply_failed_at,
       w.sync_rank::integer AS sync_rank, w.seen_key::timestamptz AS seen_key,
       p.version AS latest_version, p.rendered_at AS latest_rendered_at
FROM (
    SELECT workloads.id, workloads.region_id, workloads.provisioning_token_id, workloads.hostname, workloads.enrolled_at, workloads.credential_serial, workloads.credential_expires_at, workloads.last_renewed_at, workloads.mode, workloads.facts, workloads.agent_version, workloads.agent_capabilities, workloads.last_seen_at, workloads.sync_state, workloads.applied_policy_version, workloads.sync_error, workloads.dropped_flow_records, workloads.credential_renewal_error, workloads.last_snapshot_sent_at, workloads.last_acked_at, workloads.last_apply_failed_at,
           CASE workloads.sync_state WHEN 3 THEN 0 WHEN 4 THEN 1 WHEN 2 THEN 2 WHEN 1 THEN 3 ELSE 4 END AS sync_rank,
           coalesce(workloads.last_seen_at, '1970-01-01 00:00:00+00'::timestamptz) AS seen_key
    FROM workloads
) AS w
LEFT JOIN workload_policies p ON p.workload_id = w.id
WHERE (cardinality($1::uuid[]) = 0 OR w.id = ANY($1::uuid[]))
  AND ($2::integer = 0 OR w.mode = $2::integer)
  AND ($3::integer = 0 OR w.sync_state = $3::integer)
  AND (w.sync_rank > $4::integer
       OR (w.sync_rank = $4::integer
           AND (w.seen_key < $5::timestamptz
                OR (w.seen_key = $5::timestamptz AND w.id > $6::uuid))))
ORDER BY w.sync_rank, w.seen_key DESC, w.id
LIMIT $7
`

type ListWorkloadPageParams struct {
	WorkloadIds []uuid.UUID
	Mode        int32
	SyncState   int32
	CursorRank  int32
	CursorSeen  time.Time
	CursorID    uuid.UUID
	RowLimit    int32
}

type ListWorkloadPageRow struct {
	ID                     uuid.UUID
	RegionID               string
	ProvisioningTokenID    uuid.UUID
	Hostname               string
	EnrolledAt             time.Time
	CredentialSerial       string
	CredentialExpiresAt    time.Time
	LastRenewedAt          *time.Time
	Mode                   int32
	Facts                  []byte
	AgentVersion           string
	AgentCapabilities      []string
	LastSeenAt             *time.Time
	SyncState              int32
	AppliedPolicyVersion   int64
	SyncError              string
	DroppedFlowRecords     int64
	CredentialRenewalError string
	LastSnapshotSentAt     *time.Time
	LastAckedAt            *time.Time
	LastApplyFailedAt      *time.Time
	SyncRank               int32
	SeenKey                time.Time
	LatestVersion          pgtype.Int8
	LatestRenderedAt       *time.Time
}

// --- operator read model (ADR-0007 as amended) -------------------------------
// One page of the fleet in the order the fleet screen shows it: the
// workloads needing attention first (degraded, then offline, then
// pending, then synced), most recently seen first within a state, then by
// id. The cursor is the (rank, last seen, id) of the last row served; the
// first page passes a rank below every row. A workload never seen sorts
// as if seen at the epoch. An empty id array means every workload; a zero
// mode or sync state means any. The latest rendered version rides along
// from workload_policies so sync drift is one read.
func (q *Queries) ListWorkloadPage(ctx context.Context, arg ListWorkloadPageParams) ([]ListWorkloadPageRow, error) {
	rows, err := q.db.Query(ctx, listWorkloadPage,
		arg.WorkloadIds,
		arg.Mode,
		arg.SyncState,
		arg.CursorRank,
		arg.CursorSeen,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkloadPageRow{}
	for rows.Next() {
		var i ListWorkloadPageRow
		if err := rows.Scan(
			&i.ID,
			&i.RegionID,
			&i.ProvisioningTokenID,
			&i.Hostname,
			&i.EnrolledAt,
			&i.CredentialSerial,
			&i.CredentialExpiresAt,
			&i.LastRenewedAt,
			&i.Mode,
			&i.Facts,
			&i.AgentVersion,
			&i.AgentCapabilities,
			&i.LastSeenAt,
			&i.SyncState,
			&i.AppliedPolicyVersion,
			&i.SyncError,
			&i.DroppedFlowRecords,
			&i.CredentialRenewalError,
			&i.LastSnapshotSentAt,
			&i.LastAckedAt,
			&i.LastApplyFailedAt,
			&i.SyncRank,
			&i.SeenKey,
			&i.LatestVersion,
			&i.LatestRenderedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkloads = `-- name: ListWorkloads :many

SELECT id, region_id, provisioning_token_id, hostname, enrolled_at, credential_serial, credential_expires_at, last_renewed_at, mode, facts, agent_version, agent_capabilities, last_seen_at, sync_state, applied_policy_version, sync_error, dropped_flow_records, credential_renewal_error, last_snapshot_sent_at, last_acked_at, last_apply_failed_at FROM workloads
ORDER BY enrolled_at, id
`

// --- inventory and status (ADR-0018) ------------------------------------------
func (q *Queries) ListWorkloads(ctx context.Context) ([]Workload, error) {
	rows, err := q.db.Query(ctx, listWorkloads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workload{}
	for rows.Next() {
		var i Workload
		if err := rows.Scan(
			&i.ID,
			&i.RegionID,
			&i.ProvisioningTokenID,
			&i.Hostname,
			&i.EnrolledAt,
			&i.CredentialSerial,
			&i.CredentialExpiresAt,
			&i.LastRenewedAt,
			&i.Mode,
			&i.Facts,
			&i.AgentVersion,
			&i.AgentCapabilities,
			&i.LastSeenAt,
			&i.SyncState,
			&i.AppliedPolicyVersion,
			&i.SyncError,
			&i.DroppedFlowRecords,
			&i.CredentialRenewalError,
			&i.LastSnapshotSentAt,
			&i.LastAckedAt,
			&i.LastApplyFailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordWorkloadAgent = `-- name: RecordWorkloadAgent :execrows
UPDATE workloads
SET agent_version = $2, agent_capabilities = $3, applied_policy_version = $4, last_seen_at = $5
WHERE id = $1
`

type RecordWorkloadAgentParams struct {
	ID                   uuid.UUID
	AgentVersion         string
	AgentCapabilities    []string
	AppliedPolicyVersion int64
	LastSeenAt           *time.Time
}

func (q *Queries) RecordWorkloadAgent(ctx context.Context, arg RecordWorkloadAgentParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordWorkloadAgent,
		arg.ID,
		arg.AgentVersion,
		arg.AgentCapabilities,
		arg.AppliedPolicyVersion,
		arg.LastSeenAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordWorkloadApplied = `-- name: RecordWorkloadApplied :execrows
UPDATE workloads
SET applied_policy_version = $2, sync_state = $3, sync_error = '', last_seen_at = $4, last_acked_at = $4
WHERE id = $1
`

type RecordWorkloadAppliedParams struct {
	ID                   uuid.UUID
	AppliedPolicyVersion int64
	SyncState            int32
	LastSeenAt           *time.Time
}

// An APPLIED acknowledgement: the version, the resulting state, and the
// instant. Nothing else writes last_acked_at (migration 00007).
func (q *Queries) RecordWorkloadApplied(ctx context.Context, arg RecordWorkloadAppliedParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordWorkloadApplied,
		arg.ID,
		arg.AppliedPolicyVersion,
		arg.SyncState,
		arg.LastSeenAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordWorkloadApplyFailed = `-- name: RecordWorkloadApplyFailed :execrows
UPDATE workloads
SET sync_state = $2, sync_error = $3, last_seen_at = $4, last_apply_failed_at = $4
WHERE id = $1
`

type RecordWorkloadApplyFailedParams struct {
	ID         uuid.UUID
	SyncState  int32
	SyncError  string
	LastSeenAt *time.Time
}

// A FAILED acknowledgement: the degraded state, the agent's detail, and the
// instant. The applied version is untouched; the agent is still on it.
// Nothing else writes last_apply_failed_at (migration 00007).
func (q *Queries) RecordWorkloadApplyFailed(ctx context.Context, arg RecordWorkloadApplyFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordWorkloadApplyFailed,
		arg.ID,
		arg.SyncState,
		arg.SyncError,
		arg.LastSeenAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordWorkloadHeartbeat = `-- name: RecordWorkloadHeartbeat :execrows
UPDATE workloads
SET last_seen_at = $2, dropped_flow_records = $3, credential_renewal_error = $4
WHERE id = $1
`

type RecordWorkloadHeartbeatParams struct {
	ID                     uuid.UUID
	LastSeenAt             *time.Time
	DroppedFlowRecords     int64
	CredentialRenewalError string
}

func (q *Queries) RecordWorkloadHeartbeat(ctx context.Context, arg RecordWorkloadHeartbeatParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordWorkloadHeartbeat,
		arg.ID,
		arg.LastSeenAt,
		arg.DroppedFlowRecords,
		arg.CredentialRenewalError,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordWorkloadHeartbeatSeen = `-- name: RecordWorkloadHeartbeatSeen :execrows
UPDATE workloads
SET last_seen_at = $2
WHERE id = $1
`

type RecordWorkloadHeartbeatSeenParams struct {
	ID         uuid.UUID
	LastSeenAt *time.Time
}

func (q *Queries) RecordWorkloadHeartbeatSeen(ctx context.Context, arg RecordWorkloadHeartbeatSeenParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordWorkloadHeartbeatSeen, arg.ID, arg.LastSeenAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordWorkloadInventory = `-- name: RecordWorkloadInventory :execrows
UPDATE workloads
SET facts = $2, hostname = $3, last_seen_at = $4
WHERE id = $1
`

type RecordWorkloadInventoryParams struct {
	ID         uuid.UUID
	Facts      []byte
	Hostname   string
	LastSeenAt *time.Time
}

func (q *Queries) RecordWorkloadInventory(ctx context.Context, arg RecordWorkloadInventoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordWorkloadInventory,
		arg.ID,
		arg.Facts,
		arg.Hostname,
		arg.LastSeenAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordWorkloadRenewal = `-- name: RecordWorkloadRenewal :execrows
UPDATE workloads
SET credential_serial = $2, credential_expires_at = $3, last_renewed_at = $4
WHERE id = $1
`

type RecordWorkloadRenewalParams struct {
	ID                  uuid.UUID
	CredentialSerial    string
	CredentialExpiresAt time.Time
	LastRenewedAt       *time.Time
}

func (q *Queries) RecordWorkloadRenewal(ctx context.Context, arg RecordWorkloadRenewalParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordWorkloadRenewal,
		arg.ID,
		arg.CredentialSerial,
		arg.CredentialExpiresAt,
		arg.LastRenewedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordWorkloadSnapshotSent = `-- name: RecordWorkloadSnapshotSent :execrows
UPDATE workloads
SET last_snapshot_sent_at = $2
WHERE id = $1
`

type RecordWorkloadSnapshotSentParams struct {
	ID                 uuid.UUID
	LastSnapshotSentAt *time.Time
}

// Stamped by the sync path whenever it sends the workload a snapshot,
// whatever caused it; nothing else writes it (ADR-0018 as amended).
func (q *Queries) RecordWorkloadSnapshotSent(ctx context.Context, arg RecordWorkloadSnapshotSentParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordWorkloadSnapshotSent, arg.ID, arg.LastSnapshotSentAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setWorkloadMode = `-- name: SetWorkloadMode :execrows
UPDATE workloads
SET mode = $2
WHERE id = $1
`

type SetWorkloadModeParams struct {
	ID   uuid.UUID
	Mode int32
}

func (q *Queries) SetWorkloadMode(ctx context.Context, arg SetWorkloadModeParams) (int64, error) {
	result, err := q.db.Exec(ctx, setWorkloadMode, arg.ID, arg.Mode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setWorkloadSyncState = `-- name: SetWorkloadSyncState :execrows
UPDATE workloads
SET sync_state = $2, sync_error = $3, last_seen_at = $4
WHERE id = $1
`

type SetWorkloadSyncStateParams struct {
	ID         uuid.UUID
	SyncState  int32
	SyncError  string
	LastSeenAt *time.Time
}

func (q *Queries) SetWorkloadSyncState(ctx context.Context, arg SetWorkloadSyncStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, setWorkloadSyncState,
		arg.ID,
		arg.SyncState,
		arg.SyncError,
		arg.LastSeenAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
