// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workloads.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addWorkloadLabel = `-- name: AddWorkloadLabel :exec
INSERT INTO workload_labels (workload_id, key, value)
VALUES ($1, $2, $3)
`

type AddWorkloadLabelParams struct {
	WorkloadID uuid.UUID
	Key        string
	Value      string
}

func (q *Queries) AddWorkloadLabel(ctx context.Context, arg AddWorkloadLabelParams) error {
	_, err := q.db.Exec(ctx, addWorkloadLabel, arg.WorkloadID, arg.Key, arg.Value)
	return err
}

const createWorkload = `-- name: CreateWorkload :exec

INSERT INTO workloads (id, provisioning_token_id, hostname, enrolled_at, credential_serial, credential_expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateWorkloadParams struct {
	ID                  uuid.UUID
	ProvisioningTokenID uuid.UUID
	Hostname            string
	EnrolledAt          time.Time
	CredentialSerial    string
	CredentialExpiresAt time.Time
}

// Workload identity registry (ADR-0016). The id column is the workload_id
// carried in the credential's URI SAN; labels are assigned at enrollment from
// the provisioning token's scope and are never read from a certificate.
func (q *Queries) CreateWorkload(ctx context.Context, arg CreateWorkloadParams) error {
	_, err := q.db.Exec(ctx, createWorkload,
		arg.ID,
		arg.ProvisioningTokenID,
		arg.Hostname,
		arg.EnrolledAt,
		arg.CredentialSerial,
		arg.CredentialExpiresAt,
	)
	return err
}

const getWorkload = `-- name: GetWorkload :one
SELECT id, region_id, provisioning_token_id, hostname, enrolled_at, credential_serial, credential_expires_at, last_renewed_at FROM workloads
WHERE id = $1
`

func (q *Queries) GetWorkload(ctx context.Context, id uuid.UUID) (Workload, error) {
	row := q.db.QueryRow(ctx, getWorkload, id)
	var i Workload
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.ProvisioningTokenID,
		&i.Hostname,
		&i.EnrolledAt,
		&i.CredentialSerial,
		&i.CredentialExpiresAt,
		&i.LastRenewedAt,
	)
	return i, err
}

const listWorkloadLabels = `-- name: ListWorkloadLabels :many
SELECT workload_id, key, value FROM workload_labels
WHERE workload_id = $1
ORDER BY key
`

func (q *Queries) ListWorkloadLabels(ctx context.Context, workloadID uuid.UUID) ([]WorkloadLabel, error) {
	rows, err := q.db.Query(ctx, listWorkloadLabels, workloadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkloadLabel{}
	for rows.Next() {
		var i WorkloadLabel
		if err := rows.Scan(&i.WorkloadID, &i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordWorkloadRenewal = `-- name: RecordWorkloadRenewal :execrows
UPDATE workloads
SET credential_serial = $2, credential_expires_at = $3, last_renewed_at = $4
WHERE id = $1
`

type RecordWorkloadRenewalParams struct {
	ID                  uuid.UUID
	CredentialSerial    string
	CredentialExpiresAt time.Time
	LastRenewedAt       *time.Time
}

func (q *Queries) RecordWorkloadRenewal(ctx context.Context, arg RecordWorkloadRenewalParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordWorkloadRenewal,
		arg.ID,
		arg.CredentialSerial,
		arg.CredentialExpiresAt,
		arg.LastRenewedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
